import type { ColorOption, IconCategory } from "./types";

/**
 * Comprehensive icon list organized by category
 * This is the single source of truth for all available icons
 */
export const ICONS_BY_CATEGORY: Record<IconCategory, string[]> = {
  all: [], // Will be populated with all icons

  common: [
    "Home",
    "Star",
    "Heart",
    "Settings",
    "Search",
    "Bell",
    "Calendar",
    "Clock",
    "MapPin",
    "Globe",
    "Bookmark",
    "Tag",
    "Flag",
    "Award",
    "Target",
    "Zap",
    "Lightbulb",
    "Sun",
    "Moon",
    "Cloud",
    "Sparkles",
    "Flame",
    "Eye",
    "EyeOff",
    "Lock",
    "Unlock",
    "Key",
    "Shield",
    "ShieldCheck",
    "Info",
    "HelpCircle",
    "AlertCircle",
    "AlertTriangle",
    "Check",
    "CheckCircle",
    "CheckCircle2",
    "X",
    "XCircle",
    "Loader2",
    "RefreshCw",
    "RotateCw",
  ],

  files: [
    "File",
    "FileText",
    "FileCode",
    "FileCode2",
    "FileImage",
    "FileVideo",
    "FileAudio",
    "FilePlus",
    "FilePlus2",
    "FileMinus",
    "FileEdit",
    "FileCheck",
    "FileCheck2",
    "FileX",
    "FileX2",
    "FileSearch",
    "FileSearch2",
    "FileCog",
    "FileJson",
    "FileJson2",
    "Folder",
    "FolderOpen",
    "FolderPlus",
    "FolderMinus",
    "FolderCheck",
    "FolderX",
    "FolderSearch",
    "FolderCog",
    "Archive",
    "ArchiveX",
    "ArchiveRestore",
    "Inbox",
    "Package",
    "PackageOpen",
    "PackageCheck",
    "PackageX",
    "PackagePlus",
    "PackageMinus",
    "PackageSearch",
    "Database",
    "DatabaseBackup",
    "HardDrive",
    "HardDriveDownload",
    "HardDriveUpload",
    "Save",
    "SaveAll",
    "Download",
    "Upload",
    "Import",
    "FileUp",
    "FileDown",
    "FolderUp",
    "FolderDown",
  ],

  arrows: [
    "ArrowUp",
    "ArrowDown",
    "ArrowLeft",
    "ArrowRight",
    "ArrowUpRight",
    "ArrowUpLeft",
    "ArrowDownRight",
    "ArrowDownLeft",
    "ChevronUp",
    "ChevronDown",
    "ChevronLeft",
    "ChevronRight",
    "ChevronsUp",
    "ChevronsDown",
    "ChevronsLeft",
    "ChevronsRight",
    "ChevronsUpDown",
    "ChevronsLeftRight",
    "MoveUp",
    "MoveDown",
    "MoveLeft",
    "MoveRight",
    "MoveHorizontal",
    "MoveVertical",
    "MoveDiagonal",
    "MoveDiagonal2",
    "ArrowBigUp",
    "ArrowBigDown",
    "ArrowBigLeft",
    "ArrowBigRight",
    "CornerUpLeft",
    "CornerUpRight",
    "CornerDownLeft",
    "CornerDownRight",
    "CornerLeftUp",
    "CornerLeftDown",
    "CornerRightUp",
    "CornerRightDown",
    "Undo",
    "Undo2",
    "Redo",
    "Redo2",
  ],

  communication: [
    "MessageSquare",
    "MessageSquarePlus",
    "MessageSquareDashed",
    "MessageSquareText",
    "MessageCircle",
    "MessageCirclePlus",
    "MessagesSquare",
    "Mail",
    "MailPlus",
    "MailOpen",
    "MailCheck",
    "MailX",
    "MailSearch",
    "Send",
    "SendHorizontal",
    "Forward",
    "Reply",
    "ReplyAll",
    "Phone",
    "PhoneCall",
    "PhoneIncoming",
    "PhoneOutgoing",
    "PhoneMissed",
    "PhoneOff",
    "Video",
    "VideoOff",
    "Mic",
    "MicOff",
    "Mic2",
    "Volume",
    "Volume1",
    "Volume2",
    "VolumeX",
    "Users",
    "User",
    "UserPlus",
    "UserMinus",
    "UserCheck",
    "UserX",
    "UserCog",
    "UserCircle",
    "UserSquare",
    "CircleUser",
    "Contact",
    "Contact2",
    "AtSign",
    "Hash",
    "Share",
    "Share2",
    "Link",
    "Link2",
    "ExternalLink",
    "Paperclip",
    "QrCode",
  ],

  media: [
    "Image",
    "ImagePlus",
    "ImageMinus",
    "ImageOff",
    "Images",
    "Camera",
    "CameraOff",
    "Film",
    "Clapperboard",
    "Music",
    "Music2",
    "Music3",
    "Music4",
    "Play",
    "PlayCircle",
    "Pause",
    "PauseCircle",
    "Square",
    "StopCircle",
    "SkipBack",
    "SkipForward",
    "FastForward",
    "Rewind",
    "Shuffle",
    "Repeat",
    "Repeat1",
    "ListMusic",
    "Disc",
    "Disc2",
    "Disc3",
    "Speaker",
    "Headphones",
    "Radio",
    "RadioReceiver",
    "Tv",
    "Tv2",
    "Monitor",
    "MonitorPlay",
    "MonitorOff",
    "MonitorSmartphone",
    "Smartphone",
    "Tablet",
    "TabletSmartphone",
    "Watch",
    "Podcast",
    "Mic2",
    "Webcam",
    "ScreenShare",
    "ScreenShareOff",
    "Cast",
    "Airplay",
  ],

  design: [
    "Palette",
    "Brush",
    "PaintBucket",
    "Paintbrush",
    "Paintbrush2",
    "Pen",
    "PenLine",
    "PenTool",
    "Pencil",
    "PencilLine",
    "PencilRuler",
    "Eraser",
    "Highlighter",
    "Feather",
    "Pipette",
    "Droplet",
    "Droplets",
    "Type",
    "TypeOutline",
    "CaseLower",
    "CaseUpper",
    "CaseSensitive",
    "Bold",
    "Italic",
    "Underline",
    "Strikethrough",
    "Subscript",
    "Superscript",
    "AlignLeft",
    "AlignCenter",
    "AlignRight",
    "AlignJustify",
    "AlignVerticalJustifyStart",
    "AlignVerticalJustifyCenter",
    "AlignVerticalJustifyEnd",
    "AlignHorizontalJustifyStart",
    "AlignHorizontalJustifyCenter",
    "AlignHorizontalJustifyEnd",
    "Layers",
    "Layers2",
    "Layers3",
    "Layout",
    "LayoutDashboard",
    "LayoutGrid",
    "LayoutList",
    "LayoutTemplate",
    "LayoutPanelLeft",
    "LayoutPanelTop",
    "Grid2x2",
    "Grid3x3",
    "Crop",
    "Scissors",
    "Blend",
    "Contrast",
    "SunDim",
    "SunMedium",
    "Sparkle",
    "Wand",
    "Wand2",
    "Shapes",
    "Component",
    "Puzzle",
    "Box",
    "Boxes",
    "Frame",
    "Scaling",
    "ZoomIn",
    "ZoomOut",
    "Move",
    "Move3d",
    "Grab",
    "Hand",
    "MousePointer",
    "MousePointer2",
    "MousePointerClick",
    "Pointer",
    "Crosshair",
    "Focus",
  ],

  development: [
    "Code",
    "Code2",
    "CodeXml",
    "Braces",
    "Brackets",
    "FileCode",
    "FileCode2",
    "FileJson",
    "FileJson2",
    "Terminal",
    "TerminalSquare",
    "Command",
    "Keyboard",
    "Binary",
    "Hash",
    "Variable",
    "Regex",
    "Cpu",
    "MemoryStick",
    "CircuitBoard",
    "Chip",
    "Server",
    "ServerCog",
    "ServerCrash",
    "ServerOff",
    "Cloud",
    "CloudCog",
    "CloudOff",
    "CloudUpload",
    "CloudDownload",
    "GitBranch",
    "GitBranchPlus",
    "GitCommit",
    "GitCommitHorizontal",
    "GitCommitVertical",
    "GitCompare",
    "GitCompareArrows",
    "GitFork",
    "GitMerge",
    "GitPullRequest",
    "GitPullRequestArrow",
    "GitPullRequestClosed",
    "GitPullRequestCreate",
    "GitPullRequestDraft",
    "Github",
    "Gitlab",
    "Bug",
    "BugOff",
    "BugPlay",
    "Wrench",
    "Tool",
    "Hammer",
    "Screwdriver",
    "Settings",
    "Settings2",
    "Cog",
    "SlidersHorizontal",
    "SlidersVertical",
    "ToggleLeft",
    "ToggleRight",
    "Power",
    "PowerOff",
    "Plug",
    "Plug2",
    "PlugZap",
    "Unplug",
    "Webhook",
    "Workflow",
    "Network",
    "Route",
    "Cable",
    "Usb",
    "Wifi",
    "WifiOff",
    "Bluetooth",
    "BluetoothOff",
    "BluetoothConnected",
    "BluetoothSearching",
    "Signal",
    "SignalHigh",
    "SignalMedium",
    "SignalLow",
    "SignalZero",
    "Antenna",
    "Satellite",
    "SatelliteDish",
    "Rss",
    "Radio",
    "RadioReceiver",
    "RadioTower",
    "Podcast",
    "Construction",
    "HardHat",
  ],

  business: [
    "Briefcase",
    "BriefcaseBusiness",
    "BriefcaseMedical",
    "Building",
    "Building2",
    "Factory",
    "Landmark",
    "LandmarkDome",
    "Store",
    "Warehouse",
    "ShoppingCart",
    "ShoppingBag",
    "ShoppingBasket",
    "CreditCard",
    "Wallet",
    "Banknote",
    "DollarSign",
    "Euro",
    "PoundSterling",
    "Coins",
    "Receipt",
    "ReceiptText",
    "HandCoins",
    "HandHeart",
    "Handshake",
    "TrendingUp",
    "TrendingDown",
    "TrendingUpDown",
    "BarChart",
    "BarChart2",
    "BarChart3",
    "BarChart4",
    "BarChartHorizontal",
    "PieChart",
    "LineChart",
    "AreaChart",
    "Activity",
    "Gauge",
    "GaugeCircle",
    "Percent",
    "BadgePercent",
    "Calculator",
    "Scale",
    "Scale3d",
    "Presentation",
    "Projector",
    "Megaphone",
    "Goal",
    "Target",
    "Crosshair",
    "Crown",
    "Trophy",
    "Medal",
    "Award",
    "BadgeCheck",
    "BadgeX",
    "BadgePlus",
    "BadgeMinus",
    "BadgeAlert",
    "BadgeInfo",
    "BadgeDollarSign",
    "Verified",
    "ClipboardList",
    "ClipboardCheck",
    "ClipboardX",
    "ClipboardPen",
    "ClipboardPenLine",
    "ClipboardCopy",
    "ClipboardPaste",
    "ClipboardType",
    "ClipboardSignature",
    "FileText",
    "FileSpreadsheet",
    "FileStack",
    "Files",
    "FolderKanban",
    "Kanban",
    "KanbanSquare",
    "KanbanSquareDashed",
    "CalendarCheck",
    "CalendarCheck2",
    "CalendarClock",
    "CalendarDays",
    "CalendarRange",
    "CalendarX",
    "CalendarX2",
    "Clock",
    "Timer",
    "TimerOff",
    "TimerReset",
    "AlarmClock",
    "AlarmClockCheck",
    "AlarmClockMinus",
    "AlarmClockOff",
    "AlarmClockPlus",
    "Hourglass",
    "Milestone",
    "FolderGit",
    "FolderGit2",
  ],

  social: [
    "ThumbsUp",
    "ThumbsDown",
    "Smile",
    "SmilePlus",
    "Frown",
    "Meh",
    "Angry",
    "Laugh",
    "Annoyed",
    "Heart",
    "HeartCrack",
    "HeartHandshake",
    "HeartOff",
    "HeartPulse",
    "PartyPopper",
    "Gift",
    "Trophy",
    "Medal",
    "Crown",
    "Sparkles",
    "Flame",
    "FireExtinguisher",
    "Coffee",
    "Pizza",
    "UtensilsCrossed",
    "Utensils",
    "Beer",
    "Wine",
    "GlassWater",
    "Milk",
    "Cake",
    "CakeSlice",
    "IceCream",
    "IceCream2",
    "Cookie",
    "Candy",
    "CandyCane",
    "CandyOff",
    "Lollipop",
    "Cherry",
    "Citrus",
    "Grape",
    "Apple",
    "Banana",
    "Egg",
    "EggFried",
    "Croissant",
    "Sandwich",
    "Salad",
    "Soup",
    "Drumstick",
    "Fish",
    "Beef",
    "Ham",
    "Nut",
    "Carrot",
    "Leaf",
    "Flower",
    "Flower2",
    "Clover",
    "TreeDeciduous",
    "TreePine",
    "Trees",
    "Palmtree",
    "Cactus",
    "Sprout",
    "Vegan",
    "Dog",
    "Cat",
    "Bird",
    "Bug",
    "Rabbit",
    "Snail",
    "Squirrel",
    "Turtle",
    "Paw",
    "PawPrint",
    "Bone",
    "Baby",
    "Accessibility",
    "PersonStanding",
    "Footprints",
    "Bike",
    "Car",
    "CarFront",
    "Bus",
    "Train",
    "TrainFront",
    "TramFront",
    "Plane",
    "PlaneLanding",
    "PlaneTakeoff",
    "Ship",
    "Rocket",
    "Sailboat",
  ],

  navigation: [
    "Home",
    "Menu",
    "MenuSquare",
    "PanelLeft",
    "PanelLeftOpen",
    "PanelLeftClose",
    "PanelRight",
    "PanelRightOpen",
    "PanelRightClose",
    "PanelTop",
    "PanelTopOpen",
    "PanelTopClose",
    "PanelBottom",
    "PanelBottomOpen",
    "PanelBottomClose",
    "PanelsTopLeft",
    "PanelsLeftBottom",
    "PanelsRightBottom",
    "Sidebar",
    "SidebarOpen",
    "SidebarClose",
    "MoreHorizontal",
    "MoreVertical",
    "Ellipsis",
    "EllipsisVertical",
    "GripHorizontal",
    "GripVertical",
    "Grip",
    "Navigation",
    "Navigation2",
    "Compass",
    "Map",
    "MapPin",
    "MapPinOff",
    "MapPinned",
    "Locate",
    "LocateFixed",
    "LocateOff",
    "Crosshair",
    "Focus",
    "ScanLine",
    "Scan",
    "QrCode",
    "Maximize",
    "Maximize2",
    "Minimize",
    "Minimize2",
    "Expand",
    "Shrink",
    "Fullscreen",
    "RectangleHorizontal",
    "RectangleVertical",
    "Square",
    "SquareDashed",
    "SquareDashedBottom",
    "SquareDashedBottomCode",
    "AppWindow",
    "AppWindowMac",
    "PictureInPicture",
    "PictureInPicture2",
    "SplitSquareHorizontal",
    "SplitSquareVertical",
    "Columns2",
    "Columns3",
    "Columns4",
    "Rows2",
    "Rows3",
    "Rows4",
    "Table",
    "Table2",
    "TableProperties",
    "Sheet",
    "List",
    "ListOrdered",
    "ListChecks",
    "ListTodo",
    "ListTree",
    "ListFilter",
    "ListCollapse",
    "ListStart",
    "ListEnd",
    "ListPlus",
    "ListMinus",
    "ListRestart",
    "ListX",
    "ListVideo",
    "ListMusic",
  ],

  actions: [
    "Plus",
    "PlusCircle",
    "PlusSquare",
    "Minus",
    "MinusCircle",
    "MinusSquare",
    "X",
    "XCircle",
    "XSquare",
    "Check",
    "CheckCircle",
    "CheckCircle2",
    "CheckSquare",
    "CheckSquare2",
    "CircleCheck",
    "SquareCheck",
    "CircleX",
    "SquareX",
    "Edit",
    "Edit2",
    "Edit3",
    "Pencil",
    "PencilLine",
    "Pen",
    "PenLine",
    "PenSquare",
    "Trash",
    "Trash2",
    "Eraser",
    "Copy",
    "CopyPlus",
    "CopyMinus",
    "CopyCheck",
    "CopyX",
    "CopySlash",
    "Clipboard",
    "ClipboardCopy",
    "ClipboardPaste",
    "ClipboardCheck",
    "ClipboardX",
    "ClipboardList",
    "ClipboardPen",
    "ClipboardPenLine",
    "ClipboardType",
    "ClipboardSignature",
    "Save",
    "SaveAll",
    "Download",
    "Upload",
    "Import",
    "FileUp",
    "FileDown",
    "FolderUp",
    "FolderDown",
    "ExternalLink",
    "Share",
    "Share2",
    "Forward",
    "Reply",
    "ReplyAll",
    "CornerUpLeft",
    "CornerUpRight",
    "CornerDownLeft",
    "CornerDownRight",
    "Undo",
    "Undo2",
    "Redo",
    "Redo2",
    "RotateCcw",
    "RotateCw",
    "RefreshCcw",
    "RefreshCw",
    "RefreshCcwDot",
    "RefreshCwOff",
    "Repeat",
    "Repeat1",
    "Repeat2",
    "ArrowLeftRight",
    "ArrowUpDown",
    "Shuffle",
    "Replace",
    "ReplaceAll",
    "Filter",
    "FilterX",
    "SlidersHorizontal",
    "SlidersVertical",
    "Settings",
    "Settings2",
    "Cog",
    "Wrench",
    "Hammer",
    "Screwdriver",
    "Tool",
    "Search",
    "SearchX",
    "SearchCheck",
    "SearchCode",
    "SearchSlash",
    "ScanSearch",
    "TextSearch",
    "FileSearch",
    "FileSearch2",
    "FolderSearch",
    "FolderSearch2",
    "ZoomIn",
    "ZoomOut",
    "Expand",
    "Shrink",
    "Fullscreen",
    "Move",
    "Move3d",
    "MoveHorizontal",
    "MoveVertical",
    "MoveDiagonal",
    "MoveDiagonal2",
    "Scaling",
    "Grab",
    "GripHorizontal",
    "GripVertical",
    "Grip",
    "Lock",
    "LockOpen",
    "LockKeyhole",
    "LockKeyholeOpen",
    "Unlock",
    "UnlockKeyhole",
    "Key",
    "KeyRound",
    "KeySquare",
    "Fingerprint",
    "ScanFace",
    "ShieldCheck",
    "ShieldX",
    "ShieldAlert",
    "ShieldQuestion",
    "ShieldOff",
    "ShieldPlus",
    "ShieldMinus",
    "Eye",
    "EyeOff",
    "EyeClosed",
    "View",
    "Glasses",
    "Binoculars",
    "Telescope",
    "Microscope",
    "Focus",
    "Scan",
    "ScanLine",
    "ScanBarcode",
    "ScanText",
    "ScanEye",
    "QrCode",
    "Barcode",
    "Tag",
    "Tags",
    "Bookmark",
    "BookmarkPlus",
    "BookmarkMinus",
    "BookmarkCheck",
    "BookmarkX",
    "Flag",
    "FlagOff",
    "FlagTriangleLeft",
    "FlagTriangleRight",
    "Pin",
    "PinOff",
    "Paperclip",
    "Link",
    "Link2",
    "Link2Off",
    "Unlink",
    "Unlink2",
    "Anchor",
    "Send",
    "SendHorizontal",
    "SendToBack",
    "BringToFront",
  ],

  status: [
    "Check",
    "CheckCircle",
    "CheckCircle2",
    "CheckSquare",
    "CheckSquare2",
    "CircleCheck",
    "SquareCheck",
    "CircleCheckBig",
    "SquareCheckBig",
    "X",
    "XCircle",
    "XSquare",
    "CircleX",
    "SquareX",
    "AlertCircle",
    "AlertTriangle",
    "AlertOctagon",
    "CircleAlert",
    "TriangleAlert",
    "OctagonAlert",
    "ShieldAlert",
    "MessageSquareWarning",
    "BadgeAlert",
    "Ban",
    "CircleSlash",
    "CircleSlash2",
    "Slash",
    "CircleOff",
    "OctagonX",
    "CircleDashed",
    "CircleDot",
    "CircleDotDashed",
    "Loader",
    "Loader2",
    "LoaderCircle",
    "LoaderPinwheel",
    "RefreshCw",
    "RefreshCcw",
    "RotateCw",
    "RotateCcw",
    "Clock",
    "Timer",
    "TimerOff",
    "TimerReset",
    "Hourglass",
    "History",
    "CalendarClock",
    "ClockAlert",
    "Info",
    "CircleHelp",
    "HelpCircle",
    "BadgeInfo",
    "MessageSquareMore",
    "MessageCircleQuestion",
    "MessageCircleMore",
    "Lightbulb",
    "LightbulbOff",
    "Sparkle",
    "Sparkles",
    "Star",
    "StarHalf",
    "StarOff",
    "Heart",
    "HeartCrack",
    "HeartOff",
    "ThumbsUp",
    "ThumbsDown",
    "Verified",
    "BadgeCheck",
    "Award",
    "Trophy",
    "Medal",
    "Crown",
    "Flame",
    "Zap",
    "ZapOff",
    "Bolt",
    "Power",
    "PowerOff",
    "Activity",
    "Gauge",
    "GaugeCircle",
    "Signal",
    "SignalHigh",
    "SignalMedium",
    "SignalLow",
    "SignalZero",
    "Wifi",
    "WifiOff",
    "WifiHigh",
    "WifiLow",
    "WifiZero",
    "Bluetooth",
    "BluetoothOff",
    "BluetoothConnected",
    "BluetoothSearching",
    "Battery",
    "BatteryCharging",
    "BatteryFull",
    "BatteryMedium",
    "BatteryLow",
    "BatteryWarning",
    "Plug",
    "Plug2",
    "PlugZap",
    "Unplug",
    "Construction",
    "HardHat",
    "Wrench",
    "Hammer",
    "CirclePause",
    "CirclePlay",
    "CircleStop",
    "PlayCircle",
    "PauseCircle",
    "StopCircle",
    "SkipForward",
    "SkipBack",
    "FastForward",
    "Rewind",
  ],

  shapes: [
    "Circle",
    "CircleDot",
    "CircleDashed",
    "CircleSlash",
    "Square",
    "SquareDashed",
    "SquareSlash",
    "Triangle",
    "TriangleRight",
    "Pentagon",
    "Hexagon",
    "Octagon",
    "Diamond",
    "Star",
    "Heart",
    "Spade",
    "Club",
    "RectangleHorizontal",
    "RectangleVertical",
    "Pill",
    "Shapes",
    "Component",
    "Box",
    "Boxes",
    "Cube",
    "Cylinder",
    "Cone",
    "Pyramid",
    "Torus",
    "Sphere",
    "Globe",
    "Globe2",
    "Orbit",
    "Atom",
    "Asterisk",
    "Plus",
    "Minus",
    "X",
    "Hash",
    "Slash",
    "Percent",
    "Equal",
    "Infinity",
  ],
};

// Populate 'all' category with all unique icons
ICONS_BY_CATEGORY.all = Array.from(
  new Set(
    Object.entries(ICONS_BY_CATEGORY)
      .filter(([key]) => key !== "all")
      .flatMap(([, icons]) => icons)
  )
).sort();

/**
 * Common icons for quick access
 */
export const COMMON_ICONS = ICONS_BY_CATEGORY.common;

/**
 * Color presets organized by group
 */
export const COLOR_PRESETS: ColorOption[] = [
  // Theme colors
  { value: "default", label: "Default", group: "Theme" },
  { value: "primary", label: "Primary", group: "Theme" },
  { value: "secondary", label: "Secondary", group: "Theme" },
  { value: "accent", label: "Accent", group: "Theme" },
  { value: "muted", label: "Muted", group: "Theme" },
  { value: "destructive", label: "Destructive", group: "Theme" },

  // Reds
  { value: "#ef4444", label: "Red", group: "Basic" },
  { value: "#dc2626", label: "Dark Red", group: "Basic" },
  { value: "#f87171", label: "Light Red", group: "Basic" },
  { value: "#fca5a5", label: "Pale Red", group: "Basic" },

  // Oranges
  { value: "#f97316", label: "Orange", group: "Basic" },
  { value: "#ea580c", label: "Dark Orange", group: "Basic" },
  { value: "#fb923c", label: "Light Orange", group: "Basic" },
  { value: "#fdba74", label: "Pale Orange", group: "Basic" },

  // Yellows
  { value: "#f59e0b", label: "Amber", group: "Basic" },
  { value: "#eab308", label: "Yellow", group: "Basic" },
  { value: "#fde047", label: "Light Yellow", group: "Basic" },
  { value: "#fef08a", label: "Pale Yellow", group: "Basic" },

  // Greens
  { value: "#84cc16", label: "Lime", group: "Basic" },
  { value: "#22c55e", label: "Green", group: "Basic" },
  { value: "#10b981", label: "Emerald", group: "Basic" },
  { value: "#14b8a6", label: "Teal", group: "Basic" },
  { value: "#4ade80", label: "Light Green", group: "Basic" },

  // Blues
  { value: "#06b6d4", label: "Cyan", group: "Basic" },
  { value: "#0ea5e9", label: "Sky", group: "Basic" },
  { value: "#3b82f6", label: "Blue", group: "Basic" },
  { value: "#2563eb", label: "Dark Blue", group: "Basic" },
  { value: "#60a5fa", label: "Light Blue", group: "Basic" },

  // Purples
  { value: "#6366f1", label: "Indigo", group: "Basic" },
  { value: "#8b5cf6", label: "Violet", group: "Basic" },
  { value: "#a855f7", label: "Purple", group: "Basic" },
  { value: "#d946ef", label: "Fuchsia", group: "Basic" },
  { value: "#c084fc", label: "Light Purple", group: "Basic" },

  // Pinks
  { value: "#ec4899", label: "Pink", group: "Basic" },
  { value: "#f43f5e", label: "Rose", group: "Basic" },
  { value: "#f472b6", label: "Light Pink", group: "Basic" },

  // Neutrals
  { value: "#000000", label: "Black", group: "Neutral" },
  { value: "#ffffff", label: "White", group: "Neutral" },
  { value: "#1f2937", label: "Charcoal", group: "Neutral" },
  { value: "#374151", label: "Dark Gray", group: "Neutral" },
  { value: "#6b7280", label: "Gray", group: "Neutral" },
  { value: "#9ca3af", label: "Light Gray", group: "Neutral" },
  { value: "#d1d5db", label: "Silver", group: "Neutral" },
  { value: "#e5e7eb", label: "Pale Gray", group: "Neutral" },
];

/**
 * Background color presets (lighter versions)
 */
export const BACKGROUND_PRESETS: ColorOption[] = [
  { value: "transparent", label: "None", group: "Special" },
  { value: "inherit", label: "Inherit", group: "Special" },

  // Light backgrounds
  { value: "#fef2f2", label: "Red", group: "Light" },
  { value: "#fff7ed", label: "Orange", group: "Light" },
  { value: "#fffbeb", label: "Yellow", group: "Light" },
  { value: "#fefce8", label: "Lime", group: "Light" },
  { value: "#f0fdf4", label: "Green", group: "Light" },
  { value: "#ecfeff", label: "Cyan", group: "Light" },
  { value: "#eff6ff", label: "Blue", group: "Light" },
  { value: "#eef2ff", label: "Indigo", group: "Light" },
  { value: "#faf5ff", label: "Purple", group: "Light" },
  { value: "#fdf4ff", label: "Fuchsia", group: "Light" },
  { value: "#fdf2f8", label: "Pink", group: "Light" },
  { value: "#f9fafb", label: "Gray", group: "Light" },

  // Dark backgrounds (for dark mode)
  { value: "#450a0a", label: "Dark Red", group: "Dark" },
  { value: "#431407", label: "Dark Orange", group: "Dark" },
  { value: "#422006", label: "Dark Yellow", group: "Dark" },
  { value: "#14532d", label: "Dark Green", group: "Dark" },
  { value: "#083344", label: "Dark Cyan", group: "Dark" },
  { value: "#172554", label: "Dark Blue", group: "Dark" },
  { value: "#3b0764", label: "Dark Purple", group: "Dark" },
  { value: "#500724", label: "Dark Pink", group: "Dark" },
  { value: "#171717", label: "Dark Gray", group: "Dark" },
];

/**
 * Feature icon mappings for domain-specific icons
 */
export const FEATURE_ICONS: Record<string, string> = {
  cms: "LayoutDashboard",
  automation: "Workflow",
  database: "Database",
  data: "Database",
  menu: "Navigation",
  menus: "Navigation",
  navigation: "Navigation",
  workflow: "Workflow",
  chat: "MessageSquare",
  messaging: "MessageSquare",
  marketing: "Megaphone",
  analytics: "BarChart2",
  settings: "Settings",
  users: "Users",
  user: "User",
  files: "Files",
  folder: "Folder",
  documents: "FileText",
  calendar: "Calendar",
  tasks: "CheckSquare",
  projects: "FolderKanban",
  reports: "FileSpreadsheet",
  dashboard: "LayoutDashboard",
  integrations: "Puzzle",
  api: "Webhook",
  security: "Shield",
  billing: "CreditCard",
  notifications: "Bell",
  email: "Mail",
  templates: "LayoutTemplate",
  builder: "PenTool",
  editor: "Edit",
  media: "Image",
  storage: "HardDrive",
  backup: "DatabaseBackup",
  import: "Import",
  export: "Download",
  help: "HelpCircle",
  support: "LifeBuoy",
  feedback: "MessageSquarePlus",
  search: "Search",
  filter: "Filter",
  sort: "ArrowUpDown",
  view: "Eye",
  preview: "ScanEye",
  publish: "Send",
  archive: "Archive",
  trash: "Trash2",
  home: "Home",
  profile: "UserCircle",
  account: "User",
  logout: "LogOut",
  login: "LogIn",
};

/**
 * Category icon mappings for domain-specific categories
 */
export const CATEGORY_ICONS: Record<string, string> = {
  layout: "PanelsTopLeft",
  content: "FileText",
  media: "Image",
  navigation: "Navigation",
  action: "MousePointerClick",
  actions: "MousePointerClick",
  ui: "Component",
  templates: "LayoutTemplate",
  template: "LayoutTemplate",
  automation: "Workflow",
  database: "Database",
  data: "Database",
  form: "FileText",
  forms: "FileText",
  table: "Table",
  tables: "Table",
  list: "ListTree",
  menu: "Navigation",
  menus: "Navigation",
  integration: "Puzzle",
  integrations: "Puzzle",
  analytics: "Sparkles",
  insights: "Sparkles",
  marketing: "Megaphone",
  communication: "MessageSquare",
  social: "Heart",
  files: "Folder",
  development: "Code",
  design: "Palette",
  business: "Briefcase",
  arrows: "ArrowRight",
  status: "CheckCircle",
  shapes: "Shapes",
  common: "Star",
};

/**
 * Default icons
 */
export const DEFAULT_ICON = "HelpCircle";
export const DEFAULT_FEATURE_ICON = "LayoutDashboard";
export const DEFAULT_CATEGORY_ICON = "Component";
