/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-manifest.ts
 * Source: features.config.ts
 *
 * To update this file:
 *   1. Edit features.config.ts
 *   2. Run: pnpm run generate:manifest
 */

"use client"

import type { Id } from "@convex/_generated/dataModel"
import type { ElementType, ReactElement } from "react"
import { lazy } from "react"

import {
  ArrowUpDown,
  BarChart,
  BarChart3,
  BookOpen,
  Bot,
  Box,
  Building2,
  Calculator,
  Calendar,
  Camera,
  CheckCircle,
  CheckSquare,
  Contact,
  Database,
  DollarSign,
  FileText,
  FolderKanban,
  Headphones,
  History,
  Home,
  Layers3,
  Library,
  Lightbulb,
  LineChart,
  Megaphone,
  Menu,
  MessageSquare,
  Package,
  Plug,
  Shield,
  ShoppingCart,
  TrendingUp,
  UserCog,
  Users
} from "lucide-react"

export type AppPageComponent = (props: { workspaceId?: Id<"workspaces"> | null }) => ReactElement | null

export interface PageManifestItem {
  id: string
  componentId: string
  title: string
  description?: string
  icon?: ElementType
  color?: string
  component: React.LazyExoticComponent<React.ComponentType<any>>
  path: string
  aliases?: string[]
  patterns?: Record<string, string>
}

export const DEFAULT_PAGE_MANIFEST: PageManifestItem[] = [
  {
    id: "overview",
    componentId: "OverviewPage",
    title: "Overview",
    description: "Dashboard overview with analytics and insights",
    icon: Home,
    component: lazy(() => import("@/frontend/features/overview/page")),
    path: "/dashboard/overview",
    aliases: ["dashboard"],
    patterns: undefined,
  },
  {
    id: "communications",
    componentId: "CommunicationsPage",
    title: "Communications",
    description: "Unified communication platform with channels, direct messages, voice/video calls, and AI integrations",
    icon: MessageSquare,
    component: lazy(() => import("@/frontend/features/communications/page")),
    path: "/dashboard/communications",
    aliases: ["message", "chat"],
    patterns: undefined,
  },
  {
    id: "status",
    componentId: "StatusPage",
    title: "Status",
    description: "Share status updates with your team",
    icon: Camera,
    component: lazy(() => import("@/frontend/features/status/page")),
    path: "/dashboard/status",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "ai",
    componentId: "AIPage",
    title: "AI",
    description: "AI assistant",
    icon: Bot,
    component: lazy(() => import("@/frontend/features/ai/page")),
    path: "/dashboard/ai",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "workspace-store",
    componentId: "WorkspaceStorePage",
    title: "Workspace Store",
    description: "Manage workspace hierarchy with nested workspaces, drag & drop, and tree visualization",
    icon: Building2,
    component: lazy(async () => {
        const module = await import("@/frontend/features/workspace-store")
        const Component = module.WorkspaceStorePage
        if (!Component) {
          throw new Error("Failed to load component WorkspaceStorePage from @/frontend/features/workspace-store")
        }
        return { default: Component }
      }),
    path: "/dashboard/workspace-store",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "knowledge",
    componentId: "KnowledgePage",
    title: "Knowledge",
    description: "Centralized knowledge base with documents, articles, and AI-consumable data",
    icon: BookOpen,
    component: lazy(() => import("@/frontend/features/knowledge/page")),
    path: "/dashboard/knowledge",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "contacts",
    componentId: "ContactsPage",
    title: "Contacts",
    description: "Manage your contacts and connections",
    icon: Contact,
    component: lazy(() => import("@/frontend/features/contacts/page")),
    path: "/dashboard/contacts",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "database",
    componentId: "DatabasesPage",
    title: "Database",
    description: "Notion-style database views and management",
    icon: Database,
    component: lazy(() => import("@/frontend/features/database/page")),
    path: "/dashboard/database",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "documents",
    componentId: "DocumentsPage",
    title: "Documents",
    description: "Collaborative document editor with real-time sync (Deprecated - use Knowledge > Docs)",
    icon: FileText,
    component: lazy(() => import("@/frontend/features/documents/page")),
    path: "/dashboard/documents",
    aliases: ["doc", "file"],
    patterns: {"file":"?file=:id"},
  },
  {
    id: "menus",
    componentId: "MenuStorePage",
    title: "Menu Store",
    description: "Install and manage navigation menus",
    icon: Menu,
    component: lazy(async () => {
        const module = await import("@/frontend/features/menus")
        const Component = module.MenuStorePage
        if (!Component) {
          throw new Error("Failed to load component MenuStorePage from @/frontend/features/menus")
        }
        return { default: Component }
      }),
    path: "/dashboard/menus",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "calendar",
    componentId: "CalendarPage",
    title: "Calendar",
    description: "Team calendar with event management and scheduling",
    icon: Calendar,
    component: lazy(() => import("@/frontend/features/calendar/page")),
    path: "/dashboard/calendar",
    aliases: ["event", "deadline"],
    patterns: {"event":"event/:id"},
  },
  {
    id: "user-management",
    componentId: "UserManagementPage",
    title: "User Management",
    description: "Unified user management: members, teams, invitations, and role hierarchy",
    icon: UserCog,
    component: lazy(() => import("@/frontend/features/user-management/page")),
    path: "/dashboard/user-management",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "reports",
    componentId: "ReportsPage",
    title: "Reports",
    description: "Analytics and reporting dashboard",
    icon: BarChart,
    component: lazy(() => import("@/frontend/features/reports/page")),
    path: "/dashboard/reports",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "tasks",
    componentId: "TasksPage",
    title: "Tasks",
    description: "Task management and tracking",
    icon: CheckSquare,
    component: lazy(() => import("@/frontend/features/tasks/page")),
    path: "/dashboard/tasks",
    aliases: ["task"],
    patterns: {"task":"?id=:id"},
  },
  {
    id: "forms",
    componentId: "FormsPage",
    title: "Forms",
    description: "Build custom forms for data collection",
    icon: FileText,
    component: lazy(() => import("@/frontend/features/forms/page")),
    path: "/dashboard/forms",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "approvals",
    componentId: "ApprovalsPage",
    title: "Approvals",
    description: "Approval workflows and request management",
    icon: CheckCircle,
    component: lazy(() => import("@/frontend/features/approvals/page")),
    path: "/dashboard/approvals",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "support",
    componentId: "SupportPage",
    title: "Support",
    description: "Customer support and helpdesk ticketing system",
    icon: Headphones,
    component: lazy(() => import("@/frontend/features/support/page")),
    path: "/dashboard/support",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "projects",
    componentId: "ProjectsPage",
    title: "Projects",
    description: "Project management with team discussions",
    icon: FolderKanban,
    component: lazy(() => import("@/frontend/features/projects/page")),
    path: "/dashboard/projects",
    aliases: ["project"],
    patterns: {"project":":id"},
  },
  {
    id: "audit-log",
    componentId: "AuditLogPage",
    title: "Audit Log",
    description: "View activity logs and audit trail",
    icon: History,
    component: lazy(() => import("@/frontend/features/audit-log/page")),
    path: "/dashboard/audit-log",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "import-export",
    componentId: "ImportExportPage",
    title: "Import/Export",
    description: "Import and export data across workspace",
    icon: ArrowUpDown,
    component: lazy(() => import("@/frontend/features/import-export/page")),
    path: "/dashboard/import-export",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "integrations",
    componentId: "IntegrationsPage",
    title: "Integrations",
    description: "Connect with third-party services and APIs",
    icon: Plug,
    component: lazy(() => import("@/frontend/features/integrations/page")),
    path: "/dashboard/integrations",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "pos",
    componentId: "PosPage",
    title: "POS",
    description: "Point of Sale and retail management",
    icon: ShoppingCart,
    component: lazy(() => import("@/frontend/features/pos/page")),
    path: "/dashboard/pos",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "studio",
    componentId: "StudioPage",
    title: "Studio",
    description: "Unified visual builder combining UI design and workflow automation in a single canvas",
    icon: Layers3,
    component: lazy(() => import("@/frontend/features/studio/page")),
    path: "/dashboard/studio",
    aliases: ["builder", "automation"],
    patterns: undefined,
  },
  {
    id: "marketing",
    componentId: "MarketingPage",
    title: "Marketing",
    description: "Marketing automation and campaign management",
    icon: Megaphone,
    component: lazy(() => import("@/frontend/features/marketing/page")),
    path: "/dashboard/marketing",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "analytics",
    componentId: "AnalyticsPage",
    title: "Analytics",
    description: "Monitor your business performance with real-time analytics",
    icon: BarChart3,
    component: lazy(() => import("@/frontend/features/analytics/page")),
    path: "/dashboard/analytics",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "analytics-dashboard",
    componentId: "AnalyticsDashboardPage",
    title: "Dashboard",
    description: "Overview of key metrics",
    icon: TrendingUp,
    component: lazy(() => import("@/frontend/features/analytics/page")),
    path: "/dashboard/analytics/dashboard",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "analytics-reports",
    componentId: "AnalyticsReportsPage",
    title: "Reports",
    description: "Generate detailed reports",
    icon: FileText,
    component: lazy(() => import("@/frontend/features/analytics/page")),
    path: "/dashboard/analytics/reports",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "bi",
    componentId: "BiPage",
    title: "Business Intelligence",
    description: "Advanced analytics and business intelligence",
    icon: LineChart,
    component: lazy(() => import("@/frontend/features/bi/page")),
    path: "/dashboard/bi",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "sales",
    componentId: "SalesPage",
    title: "Sales",
    description: "Sales management and pipeline tracking",
    icon: DollarSign,
    component: lazy(() => import("@/frontend/features/sales/page")),
    path: "/dashboard/sales",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "hr",
    componentId: "hrPage",
    title: "HR Management",
    description: "Human Resources Management",
    icon: Users,
    component: lazy(() => import("@/frontend/features/hr/page")),
    path: "/dashboard/hr",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "content",
    componentId: "ContentPage",
    title: "Content Library",
    description: "Centralized content management for images, videos, audio, and documents with AI generation capabilities.",
    icon: Library,
    component: lazy(() => import("@/frontend/features/content/page")),
    path: "/dashboard/content",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "cms-lite",
    componentId: "CmsLitePage",
    title: "Cms Lite",
    description: "Cms Lite feature",
    icon: Box,
    component: lazy(() => import("@/frontend/features/cms-lite/page")),
    path: "/dashboard/cms-lite",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "accounting",
    componentId: "accountingPage",
    title: "Accounting",
    description: "Financial Management and Accounting",
    icon: Calculator,
    component: lazy(() => import("@/frontend/features/accounting/page")),
    path: "/dashboard/accounting",
    aliases: ["finance"],
    patterns: {"invoice":"invoices/:id","expense":"expenses/:id"},
  },
  {
    id: "inventory",
    componentId: "InventoryPage",
    title: "Inventory Management",
    description: "Comprehensive inventory management with multi-warehouse support, stock tracking, and demand forecasting",
    icon: Package,
    component: lazy(() => import("@/frontend/features/inventory/page")),
    path: "/dashboard/erp/inventory",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "crm",
    componentId: "CrmPage",
    title: "CRM",
    description: "Customer Relationship Management with contacts, leads, opportunities, and sales pipeline",
    icon: Users,
    component: lazy(() => import("@/frontend/features/crm/page")),
    path: "/dashboard/erp/crm",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "platform-admin",
    componentId: "PlatformAdminPage",
    title: "Platform Admin",
    description: "Super Admin panel for managing features, workspaces, and system configuration",
    icon: Shield,
    component: lazy(() => import("@/frontend/features/platform-admin/page")),
    path: "/dashboard/platform-admin",
    aliases: undefined,
    patterns: undefined,
  },
  {
    id: "example",
    componentId: "ExamplePage",
    title: "Example Feature",
    description: "A minimal example feature demonstrating SuperSpace patterns and conventions",
    icon: Lightbulb,
    component: lazy(() => import("@/frontend/features/example/page")),
    path: "/dashboard/example",
    aliases: undefined,
    patterns: undefined,
  }
]

export const PAGE_MANIFEST_MAP: Record<string, PageManifestItem> = Object.fromEntries(
  DEFAULT_PAGE_MANIFEST.map((p) => [p.id, p]),
)

export const COMPONENT_REGISTRY_MAP: Record<string, PageManifestItem> = Object.fromEntries(
  DEFAULT_PAGE_MANIFEST.map((p) => [p.componentId, p]),
)

export const RESOURCE_TO_FEATURE_MAP: Record<string, string> = {
  "dashboard": "overview",
  "message": "communications",
  "chat": "communications",
  "doc": "documents",
  "file": "documents",
  "event": "calendar",
  "deadline": "calendar",
  "task": "tasks",
  "project": "projects",
  "builder": "studio",
  "automation": "studio",
  "finance": "accounting",
  "invoice": "accounting",
  "expense": "accounting"
}

export function getDefaultPages(): PageManifestItem[] {
  return DEFAULT_PAGE_MANIFEST
}

export function getPageById(id: string): PageManifestItem | undefined {
  return DEFAULT_PAGE_MANIFEST.find((p) => p.id === id)
}

export function getComponentById(componentId: string): PageManifestItem | undefined {
  return COMPONENT_REGISTRY_MAP[componentId]
}

interface AppContentProps {
  workspaceId?: Id<"workspaces"> | null
  activeView: string
}

export function AppContent({ workspaceId, activeView }: AppContentProps) {
  const fallbackPage =
    DEFAULT_PAGE_MANIFEST.find((p) => p.id === activeView) ?? DEFAULT_PAGE_MANIFEST.find((p) => p.id === "overview")

  if (!fallbackPage) {
    return <div className="flex-1 p-8">Page not found: {activeView}</div>
  }

  const Comp = fallbackPage.component
  return (
    <div className="flex-1 overflow-hidden">
      <Comp workspaceId={workspaceId ?? null} />
    </div>
  )
}
