/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/generate-manifest.ts
 * Source: features.config.ts
 *
 * To update this file:
 *   1. Edit features.config.ts
 *   2. Run: pnpm run generate:manifest
 */

"use client"

import type { Id } from "@convex/_generated/dataModel"
import type { ElementType, ReactElement } from "react"
import { lazy } from "react"

import {
  Archive,
  BarChart,
  BarChart3,
  Bell,
  Bot,
  Box,
  CheckSquare,
  Database,
  FileText,
  FolderKanban,
  Hammer,
  Headphones,
  Heart,
  Home,
  Mail,
  Menu,
  MessageCircle,
  Phone,
  Settings,
  Shield,
  Star,
  User,
  Users,
  Workflow,
  Zap
} from "lucide-react"

export type AppPageComponent = (props: { workspaceId?: Id<"workspaces"> | null }) => ReactElement | null

export interface PageManifestItem {
  id: string
  componentId: string
  title: string
  description?: string
  icon?: ElementType
  color?: string
  component: React.LazyExoticComponent<React.ComponentType<any>>
}

export const DEFAULT_PAGE_MANIFEST: PageManifestItem[] = [
  {
    id: "overview",
    componentId: "OverviewPage",
    title: "Overview",
    description: "Dashboard overview with analytics and insights",
    icon: Home,
    component: lazy(() => import("@/frontend/features/overview/page")),
  },
  {
    id: "chat",
    componentId: "ChatsPage",
    title: "Chat",
    description: "Chat conversations",
    icon: MessageCircle,
    component: lazy(() => import("@/frontend/features/chat/page")),
  },
  {
    id: "calls",
    componentId: "CallsPage",
    title: "Calls",
    description: "Voice and video calls",
    icon: Phone,
    component: lazy(() => import("@/frontend/features/calls/page")),
  },
  {
    id: "status",
    componentId: "StatusPage",
    title: "Status",
    description: "Share status updates with your team",
    icon: Zap,
    component: lazy(() => import("@/frontend/features/status/page")),
  },
  {
    id: "members",
    componentId: "MembersPage",
    title: "Members",
    description: "Manage workspace members and permissions",
    icon: Users,
    component: lazy(() => import("@/frontend/features/members/page")),
  },
  {
    id: "ai",
    componentId: "AIPage",
    title: "AI",
    description: "AI assistant",
    icon: Bot,
    component: lazy(() => import("@/frontend/features/ai/page")),
  },
  {
    id: "starred",
    componentId: "StarredPage",
    title: "Starred",
    description: "Starred messages",
    icon: Star,
    component: lazy(() => import("@/frontend/features/starred/page")),
  },
  {
    id: "friends",
    componentId: "FriendsPage",
    title: "Friends",
    description: "Manage your friends and connections",
    icon: Heart,
    component: lazy(() => import("@/frontend/features/friends/page")),
  },
  {
    id: "archived",
    componentId: "ArchivedPage",
    title: "Archived",
    description: "Archived chats",
    icon: Archive,
    component: lazy(() => import("@/frontend/features/archived/page")),
  },
  {
    id: "database",
    componentId: "DatabasesPage",
    title: "Database",
    description: "Notion-style database views and management",
    icon: Database,
    component: lazy(() => import("@/frontend/features/database/page")),
  },
  {
    id: "documents",
    componentId: "DocumentsPage",
    title: "Documents",
    description: "Collaborative document editor with real-time sync",
    icon: FileText,
    component: lazy(() => import("@/frontend/features/documents/page")),
  },
  {
    id: "menus",
    componentId: "MenusPage",
    title: "Menu Store",
    description: "Install and manage navigation menus",
    icon: Menu,
    component: lazy(() => import("@/frontend/features/menu-store/page")),
  },
  {
    id: "invitations",
    componentId: "InvitationsPage",
    title: "Invitations",
    description: "Manage workspace invitations",
    icon: Mail,
    component: lazy(() => import("@/frontend/features/invitations/page")),
  },
  {
    id: "reports",
    componentId: "ReportsPage",
    title: "Reports",
    description: "Analytics and reporting dashboard",
    icon: BarChart,
    component: lazy(() => import("@/frontend/features/reports/views/ReportsPage")),
  },
  {
    id: "tasks",
    componentId: "TasksPage",
    title: "Tasks",
    description: "Task management and tracking",
    icon: CheckSquare,
    component: lazy(() => import("@/frontend/features/tasks/views/TasksPage")),
  },
  {
    id: "support",
    componentId: "SupportPage",
    title: "Support",
    description: "Customer support and helpdesk ticketing system",
    icon: Headphones,
    component: lazy(() => import("@/frontend/features/support/page")),
  },
  {
    id: "projects",
    componentId: "ProjectsPage",
    title: "Projects",
    description: "Project management with team discussions",
    icon: FolderKanban,
    component: lazy(() => import("@/frontend/features/projects/page")),
  },
  {
    id: "crm",
    componentId: "CRMPage",
    title: "CRM",
    description: "Customer relationship management with integrated chat",
    icon: Users,
    component: lazy(() => import("@/frontend/features/crm/page")),
  },
  {
    id: "notifications",
    componentId: "NotificationsPage",
    title: "Notifications",
    description: "System notifications and activity feed",
    icon: Bell,
    component: lazy(() => import("@/frontend/features/notifications/page")),
  },
  {
    id: "user-settings",
    componentId: "ProfilePage",
    title: "Profile",
    description: "Manage your user profile and preferences",
    icon: User,
    component: lazy(() => import("@/frontend/features/user-settings/page")),
  },
  {
    id: "analytics",
    componentId: "AnalyticsPage",
    title: "Analytics",
    description: "Monitor your business performance with real-time analytics",
    icon: BarChart3,
    component: lazy(() => import("@/frontend/features/analytics/page")),
  },
  {
    id: "automation",
    componentId: "AutomationPage",
    title: "Automation",
    description: "Automate workflows and processes with visual builders",
    icon: Workflow,
    component: lazy(() => import("@/frontend/features/automation/page")),
  },
  {
    id: "settings",
    componentId: "WorkspacesPage",
    title: "Settings",
    description: "Workspace configuration and settings",
    icon: Settings,
    component: lazy(() => import("@/frontend/features/workspace-settings/page")),
  },
  {
    id: "cms-lite",
    componentId: "CmsLitePage",
    title: "Cms Lite",
    description: "Cms Lite feature",
    icon: Box,
    component: lazy(() => import("@/frontend/features/cms-lite/views/CmsLitePage")),
  },
  {
    id: "builder",
    componentId: "BuilderPage",
    title: "Builder",
    description: "Build apps, content, and interfaces with visual builder tools",
    icon: Hammer,
    component: lazy(() => import("@/frontend/features/builder/page")),
  },
  {
    id: "platform-admin",
    componentId: "PlatformAdminPage",
    title: "Platform Admin",
    description: "Super Admin panel for managing features, workspaces, and system configuration",
    icon: Shield,
    component: lazy(() => import("@/frontend/features/platform-admin/views/PlatformAdminPage")),
  }
]

export const PAGE_MANIFEST_MAP: Record<string, PageManifestItem> = Object.fromEntries(
  DEFAULT_PAGE_MANIFEST.map((p) => [p.id, p]),
)

export const COMPONENT_REGISTRY_MAP: Record<string, PageManifestItem> = Object.fromEntries(
  DEFAULT_PAGE_MANIFEST.map((p) => [p.componentId, p]),
)

export function getDefaultPages(): PageManifestItem[] {
  return DEFAULT_PAGE_MANIFEST
}

export function getPageById(id: string): PageManifestItem | undefined {
  return DEFAULT_PAGE_MANIFEST.find((p) => p.id === id)
}

export function getComponentById(componentId: string): PageManifestItem | undefined {
  return COMPONENT_REGISTRY_MAP[componentId]
}

interface AppContentProps {
  workspaceId?: Id<"workspaces"> | null
  activeView: string
}

export function AppContent({ workspaceId, activeView }: AppContentProps) {
  const fallbackPage =
    DEFAULT_PAGE_MANIFEST.find((p) => p.id === activeView) ?? DEFAULT_PAGE_MANIFEST.find((p) => p.id === "overview")

  if (!fallbackPage) {
    return <div className="flex-1 p-8">Page not found: {activeView}</div>
  }

  const Comp = fallbackPage.component
  return (
    <div className="flex-1 overflow-hidden">
      <Comp workspaceId={workspaceId ?? null} />
    </div>
  )
}
