#!/usr/bin/env tsx
/**
 * Auto-generate lib/features/registry.ts
 *
 * This script scans feature config files and produces the client-side registry
 * with explicit imports so that Next.js can statically analyze dependencies.
 *
 * Usage:
 *   pnpm run generate:registry
 *
 * This script is invoked automatically from `pnpm run sync:all`.
 */

import fs from "fs"
import path from "path"
import { pathToFileURL } from "url"
import { globSync } from "glob"

import type { FeatureConfig } from "../../lib/features/defineFeature"

const ROOT_DIR = process.cwd()
const OUTPUT_PATH = path.join(ROOT_DIR, "lib/features/registry.ts")
const CONFIG_GLOB = "frontend/features/*/config.ts"

interface FeatureEntry {
  slug: string
  importName: string
  importPath: string
  feature: FeatureConfig
}

function toIdentifier(slug: string): string {
  const parts = slug
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)

  if (parts.length === 0) {
    return "feature"
  }

  const [first, ...rest] = parts
  const base =
    first.charAt(0).toLowerCase() + first.slice(1).toLowerCase()
  const tail = rest
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join("")

  const identifier = `${base}${tail}`.replace(/^[^a-zA-Z_]/, "_")
  return identifier || "feature"
}

async function loadFeatureEntries(): Promise<FeatureEntry[]> {
  const configPaths = globSync(CONFIG_GLOB, {
    cwd: ROOT_DIR,
    windowsPathsNoEscape: true,
  })

  if (configPaths.length === 0) {
    throw new Error("No feature config files found under frontend/features/*/config.ts")
  }

  const entries: FeatureEntry[] = []

  for (const relativePath of configPaths) {
    const normalizedPath = relativePath.replace(/\\/g, "/")
    const slug = path.basename(path.dirname(normalizedPath))
    const absolutePath = path.join(ROOT_DIR, normalizedPath)
    const moduleUrl = pathToFileURL(absolutePath).href

    const module = await import(moduleUrl)
    const feature = module.default as FeatureConfig | undefined

    if (!feature) {
      throw new Error(`Feature config at ${normalizedPath} does not have a default export`)
    }

    const importName = `${toIdentifier(slug)}Config`
    const importPath = `@/${normalizedPath.replace(/\.tsx?$/, "")}`

    entries.push({
      slug,
      importName,
      importPath,
      feature,
    })
  }

  entries.sort((a, b) => a.feature.ui.order - b.feature.ui.order)
  return entries
}

function formatImportStatements(entries: FeatureEntry[]): string {
  return entries
    .map(entry => `import ${entry.importName} from '${entry.importPath}'`)
    .join("\n")
}

function formatFeatureArray(entries: FeatureEntry[]): string {
  return `const featureConfigs: FeatureConfig[] = [
${entries.map(entry => `  ${entry.importName},`).join("\n")}
]`
}

function generateRegistryContent(entries: FeatureEntry[]): string {
  const header = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-registry.ts
 * Source of truth: frontend/features/[feature]/config.ts
 *
 * To update this file, modify feature config files and run:
 *   pnpm run sync:all
 */

import type { FeatureConfig } from './defineFeature'

${formatImportStatements(entries)}

${formatFeatureArray(entries)}
`

  const body = `
/**
 * Extract and validate all discovered features
 */
export const DISCOVERED_FEATURES: FeatureConfig[] = [...featureConfigs].sort(
  (a, b) => a.ui.order - b.ui.order
)

/**
 * Get all registered features
 */
export function getAllFeatures(): FeatureConfig[] {
  return DISCOVERED_FEATURES
}

/**
 * Get feature by ID
 */
export function getFeatureById(id: string): FeatureConfig | undefined {
  const findFeature = (features: FeatureConfig[]): FeatureConfig | undefined => {
    for (const feature of features) {
      if (feature.id === id) return feature
      if (feature.children) {
        const found = findFeature(feature.children)
        if (found) return found
      }
    }
    return undefined
  }
  return findFeature(DISCOVERED_FEATURES)
}

/**
 * Get features by category
 */
export function getFeaturesByCategory(category: string): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.ui.category === category)
}

/**
 * Get features by type (default, optional, etc.)
 */
export function getFeaturesByType(
  type: 'default' | 'system' | 'optional' | 'experimental'
): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.technical.featureType === type)
}

/**
 * Get features by status
 */
export function getFeaturesByStatus(
  status: 'stable' | 'beta' | 'development' | 'experimental' | 'deprecated'
): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.status.state === status)
}

/**
 * Get all ready features (isReady = true)
 */
export function getReadyFeatures(): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.status.isReady)
}

/**
 * Get all feature IDs (flat list)
 */
export function getAllFeatureIds(): string[] {
  const collectIds = (features: FeatureConfig[]): string[] => {
    return features.flatMap(f => [f.id, ...(f.children ? collectIds(f.children) : [])])
  }
  return collectIds(DISCOVERED_FEATURES)
}

/**
 * Validate registry for duplicates and issues
 */
export function validateRegistry(): { valid: boolean; errors: string[] } {
  const errors: string[] = []
  const ids = getAllFeatureIds()
  const duplicates = ids.filter((id, index) => ids.indexOf(id) !== index)

  if (duplicates.length > 0) {
    errors.push(\`Duplicate feature IDs found: \${duplicates.join(', ')}\`)
  }

  const paths = DISCOVERED_FEATURES.map(f => f.ui.path)
  const duplicatePaths = paths.filter((path, index) => paths.indexOf(path) !== index)
  if (duplicatePaths.length > 0) {
    errors.push(\`Duplicate paths found: \${duplicatePaths.join(', ')}\`)
  }

  return {
    valid: errors.length === 0,
    errors,
  }
}

/**
 * Backward compatibility exports
 * @deprecated Use DISCOVERED_FEATURES instead
 */
export const FEATURES_REGISTRY = DISCOVERED_FEATURES

/**
 * Convert to legacy features.config.ts format
 * @deprecated Will be removed when legacy manifest is retired
 */
export function toLegacyFormat() {
  return DISCOVERED_FEATURES.map(f => ({
    slug: f.id,
    name: f.name,
    description: f.description,
    featureType: f.technical.featureType,
    category: f.ui.category,
    icon: f.ui.icon,
    path: f.ui.path,
    component: f.ui.component,
    order: f.ui.order,
    type: 'route' as const,
    version: f.technical.version,
    hasUI: f.technical.hasUI,
    hasConvex: f.technical.hasConvex,
    hasTests: f.technical.hasTests,
    tags: f.tags,
    status: f.status.state,
    isReady: f.status.isReady,
    children: f.children?.map(c => ({
      slug: c.id,
      name: c.name,
      description: c.description,
      featureType: c.technical.featureType,
      category: c.ui.category,
      icon: c.ui.icon,
      path: c.ui.path,
      component: c.ui.component,
      order: c.ui.order,
      type: 'route' as const,
      version: c.technical.version,
      hasUI: c.technical.hasUI,
      hasConvex: c.technical.hasConvex,
      hasTests: c.technical.hasTests,
    })),
  }))
}

if (process.env.NODE_ENV !== 'production') {
  const validation = validateRegistry()
  if (!validation.valid) {
    console.error('Feature Registry Validation Failed:')
    validation.errors.forEach(err => console.error(\`  - \${err}\`))
  } else {
    console.log(\`Feature Registry: \${DISCOVERED_FEATURES.length} features discovered\`)
  }
}
`

  return `${header.trim()}\n${body.trim()}\n`
}

async function main() {
  console.log("Generating lib/features/registry.ts from feature configs...")

  const entries = await loadFeatureEntries()

  const duplicateSlugs = entries
    .map(entry => entry.feature.id)
    .filter((id, index, arr) => arr.indexOf(id) !== index)

  if (duplicateSlugs.length > 0) {
    throw new Error(`Duplicate feature ids detected: ${duplicateSlugs.join(", ")}`)
  }

  const content = generateRegistryContent(entries)
  fs.writeFileSync(OUTPUT_PATH, `${content}\n`, "utf-8")

  console.log(`Wrote ${entries.length} feature imports to ${OUTPUT_PATH}`)
}

main().catch(error => {
  console.error("Failed to generate feature registry:", error)
  process.exit(1)
})
