/**
 * AI Empty State Component
 * Welcome/empty state for AI chat
 * @module shared/communications/chat/components/ai/AIEmptyState
 */

"use client";

import React from "react";
import { Bot, Sparkles, Code, FileText, MessageSquare, Lightbulb } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

export interface AIEmptyStateProps {
  variant?: "welcome" | "no-session" | "empty-thread";
  onNewChat?: () => void;
  onSuggestionClick?: (suggestion: string) => void;
  className?: string;
}

const suggestions = [
  {
    icon: Code,
    text: "Help me write code",
    prompt: "Can you help me write code for...",
  },
  {
    icon: FileText,
    text: "Summarize a document",
    prompt: "Please summarize the following document...",
  },
  {
    icon: Lightbulb,
    text: "Brainstorm ideas",
    prompt: "Help me brainstorm ideas for...",
  },
  {
    icon: MessageSquare,
    text: "Explain a concept",
    prompt: "Can you explain...",
  },
];

/**
 * AI empty state component with suggestions
 */
export function AIEmptyState({
  variant = "welcome",
  onNewChat,
  onSuggestionClick,
  className,
}: AIEmptyStateProps) {
  if (variant === "no-session") {
    return (
      <div className={cn("flex-1 flex flex-col items-center justify-center p-8", className)}>
        <div className="h-24 w-24 mb-6 bg-gradient-to-br from-blue-600 to-purple-600 rounded-full flex items-center justify-center">
          <Bot className="h-12 w-12 text-white" />
        </div>
        <h2 className="text-xl font-semibold text-foreground mb-2">
          Ask AI anything
        </h2>
        <p className="text-muted-foreground text-center mb-6 max-w-sm">
          Get help with writing, learning, brainstorming, coding, and more.
        </p>
        <div className="text-xs text-muted-foreground text-center">
          Messages are generated by AI. Some may be inaccurate or inappropriate.
        </div>
      </div>
    );
  }

  if (variant === "empty-thread") {
    return (
      <div className={cn("flex-1 flex flex-col items-center justify-center p-8", className)}>
        <Sparkles className="h-12 w-12 text-primary mb-4" />
        <h3 className="font-medium text-foreground mb-2">Start the conversation</h3>
        <p className="text-sm text-muted-foreground text-center">
          Type a message below to begin chatting with AI.
        </p>
      </div>
    );
  }

  // Default: welcome with suggestions
  return (
    <div className={cn("flex-1 flex flex-col items-center justify-center p-8", className)}>
      <div className="h-20 w-20 mb-6 bg-gradient-to-br from-blue-600 to-purple-600 rounded-full flex items-center justify-center">
        <Bot className="h-10 w-10 text-white" />
      </div>
      
      <h2 className="text-xl font-semibold text-foreground mb-2">
        How can I help you today?
      </h2>
      <p className="text-muted-foreground text-center mb-8 max-w-sm">
        I can assist with writing, coding, learning, and much more.
      </p>

      {/* Suggestions */}
      {onSuggestionClick && (
        <div className="grid grid-cols-2 gap-3 w-full max-w-md">
          {suggestions.map((suggestion, index) => {
            const Icon = suggestion.icon;
            return (
              <Button
                key={index}
                variant="outline"
                className="h-auto py-3 px-4 justify-start gap-3"
                onClick={() => onSuggestionClick(suggestion.prompt)}
              >
                <Icon className="h-4 w-4 text-muted-foreground" />
                <span className="text-sm">{suggestion.text}</span>
              </Button>
            );
          })}
        </div>
      )}

      {onNewChat && !onSuggestionClick && (
        <Button onClick={onNewChat} className="gap-2">
          <Sparkles className="h-4 w-4" />
          Start new chat
        </Button>
      )}
    </div>
  );
}

export default AIEmptyState;
