/**
 * ERP Inventory Module Configuration
 * Auto-discovered by the ERP system
 */

import { createModuleConfig } from '@/lib/module-config';
import type { ModuleConfig } from '@/types/module';

const inventoryConfig: ModuleConfig = createModuleConfig({
  // Module metadata
  name: 'inventory',
  displayName: 'Inventory Management',
  description: 'Comprehensive inventory and warehouse management system',
  version: '1.0.0',
  category: 'erp',

  // Module icon and visual
  icon: 'package',
  emoji: '📦',
  color: 'orange',

  // Route configuration
  route: '/erp/inventory',

  // Module type
  moduleType: 'feature',
  hasUI: true,
  hasConvex: true,
  hasTests: false,
  hasSettings: true,

  // Module status
  state: 'active',
  isReady: true,
  isCore: true,

  // Module order
  order: 40,

  // Dependencies
  dependsOn: ['workspaces', 'users', 'shared-search', 'shared-attachments', 'shared-activity'],

  // Features provided
  provides: [
    'inventory-items',
    'stock-management',
    'warehouse-management',
    'purchase-orders',
    'suppliers',
    'inventory-reports',
    'stock-adjustments',
    'inventory-transfers',
    'barcode-scanning',
    'stock-forecasts',
  ],

  // Sub-modules
  subModules: [
    {
      id: 'items',
      name: 'Items',
      displayName: 'Items & Products',
      description: 'Manage inventory items and products',
      icon: 'box',
      route: '/erp/inventory/items',
      component: 'ItemsPage',
      order: 1,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40],
        update: [10, 20, 30],
        delete: [10, 20],
        export: [10, 20, 30, 40],
        import: [10, 20, 30],
      },
    },
    {
      id: 'stock',
      name: 'stock',
      displayName: 'Stock Management',
      description: 'Track inventory levels and stock movements',
      icon: 'activity',
      route: '/erp/inventory/stock',
      component: 'StockPage',
      order: 2,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40],
        update: [10, 20, 30],
        delete: [10, 20],
        adjust: [10, 20, 30],
        transfer: [10, 20, 30, 40],
      },
    },
    {
      id: 'warehouses',
      name: 'warehouses',
      displayName: 'Warehouses',
      description: 'Manage multiple warehouses and locations',
      icon: 'building',
      route: '/erp/inventory/warehouses',
      component: 'WarehousesPage',
      order: 3,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30],
        update: [10, 20, 30],
        delete: [10, 20],
      },
    },
    {
      id: 'purchase-orders',
      name: 'purchase-orders',
      displayName: 'Purchase Orders',
      description: 'Create and manage purchase orders',
      icon: 'file-text',
      route: '/erp/inventory/purchase-orders',
      component: 'PurchaseOrdersPage',
      order: 4,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40],
        update: [10, 20, 30],
        delete: [10, 20],
        approve: [10, 20, 30],
        receive: [10, 20, 30, 40],
      },
    },
    {
      id: 'suppliers',
      name: 'suppliers',
      displayName: 'Suppliers',
      description: 'Manage supplier information and relationships',
      icon: 'truck',
      route: '/erp/inventory/suppliers',
      component: 'SuppliersPage',
      order: 5,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40],
        update: [10, 20, 30],
        delete: [10, 20],
      },
    },
    {
      id: 'adjustments',
      name: 'adjustments',
      displayName: 'Stock Adjustments',
      description: 'Manual stock adjustments and corrections',
      icon: 'edit',
      route: '/erp/inventory/adjustments',
      component: 'AdjustmentsPage',
      order: 6,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30],
        update: [10, 20, 30],
        delete: [10, 20],
      },
    },
    {
      id: 'transfers',
      name: 'transfers',
      displayName: 'Stock Transfers',
      description: 'Transfer stock between warehouses',
      icon: 'arrow-right-left',
      route: '/erp/inventory/transfers',
      component: 'TransfersPage',
      order: 7,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40],
        update: [10, 20, 30],
        delete: [10, 20],
        approve: [10, 20, 30],
      },
    },
    {
      id: 'reports',
      name: 'reports',
      displayName: 'Reports & Analytics',
      description: 'Inventory reports and analytics',
      icon: 'bar-chart',
      route: '/erp/inventory/reports',
      component: 'InventoryReportsPage',
      order: 8,
      permissions: {
        read: [10, 20, 30, 40, 50],
        export: [10, 20, 30, 40],
      },
    },
  ],

  // API endpoints
  api: {
    base: '/api/erp/inventory',
    endpoints: {
      items: {
        list: 'GET /items',
        get: 'GET /items/:id',
        create: 'POST /items',
        update: 'PUT /items/:id',
        delete: 'DELETE /items/:id',
        adjust: 'POST /items/:id/adjust',
        transfer: 'POST /items/:id/transfer',
        barcode: 'GET /items/barcode/:code',
      },
      stock: {
        levels: 'GET /stock/levels',
        movements: 'GET /stock/movements',
        adjust: 'POST /stock/adjust',
        forecast: 'GET /stock/forecast',
        reorder: 'GET /stock/reorder-points',
      },
      warehouses: {
        list: 'GET /warehouses',
        get: 'GET /warehouses/:id',
        create: 'POST /warehouses',
        update: 'PUT /warehouses/:id',
        delete: 'DELETE /warehouses/:id',
        stock: 'GET /warehouses/:id/stock',
      },
      purchaseOrders: {
        list: 'GET /purchase-orders',
        get: 'GET /purchase-orders/:id',
        create: 'POST /purchase-orders',
        update: 'PUT /purchase-orders/:id',
        delete: 'DELETE /purchase-orders/:id',
        approve: 'POST /purchase-orders/:id/approve',
        receive: 'POST /purchase-orders/:id/receive',
        pdf: 'GET /purchase-orders/:id/pdf',
      },
      suppliers: {
        list: 'GET /suppliers',
        get: 'GET /suppliers/:id',
        create: 'POST /suppliers',
        update: 'PUT /suppliers/:id',
        delete: 'DELETE /suppliers/:id',
        items: 'GET /suppliers/:id/items',
        history: 'GET /suppliers/:id/history',
      },
      adjustments: {
        list: 'GET /adjustments',
        get: 'GET /adjustments/:id',
        create: 'POST /adjustments',
        update: 'PUT /adjustments/:id',
        delete: 'DELETE /adjustments/:id',
        approve: 'POST /adjustments/:id/approve',
      },
      transfers: {
        list: 'GET /transfers',
        get: 'GET /transfers/:id',
        create: 'POST /transfers',
        update: 'PUT /transfers/:id',
        delete: 'DELETE /transfers/:id',
        approve: 'POST /transfers/:id/approve',
        complete: 'POST /transfers/:id/complete',
      },
      reports: {
        inventory: 'GET /reports/inventory',
        stock: 'GET /reports/stock',
        movements: 'GET /reports/movements',
        valuation: 'GET /reports/valuation',
        forecast: 'GET /reports/forecast',
        suppliers: 'GET /reports/suppliers',
      },
    },
  },

  // Database tables
  tables: [
    // Core tables
    'inventoryItems',
    'inventoryCategories',
    'stockLevels',
    'stockMovements',
    'stockAdjustments',
    'warehouses',
    'warehouseLocations',
    'purchaseOrders',
    'purchaseOrderItems',
    'suppliers',
    'supplierItems',
    'inventoryTransfers',
    'transferItems',

    // Supporting tables
    'itemVariants',
    'itemImages',
    'inventoryValuations',
    'reorderPoints',
    'stockForecasts',
    'batchNumbers',
    'serialNumbers',
    'inventoryAudits',
    'supplierPriceLists',
    'itemSuppliers',
  ],

  // Settings configuration
  settings: {
    groups: [
      {
        name: 'general',
        label: 'General Settings',
        icon: 'settings',
        order: 1,
        settings: [
          {
            key: 'defaultWarehouse',
            type: 'select',
            label: 'Default Warehouse',
            description: 'Default warehouse for inventory operations',
            required: false,
            optionsSource: 'warehouses',
          },
          {
            key: 'trackSerialNumbers',
            type: 'boolean',
            label: 'Track Serial Numbers',
            description: 'Enable serial number tracking for items',
            required: false,
            default: false,
          },
          {
            key: 'trackBatchNumbers',
            type: 'boolean',
            label: 'Track Batch Numbers',
            description: 'Enable batch/lot tracking for items',
            required: false,
            default: false,
          },
          {
            key: 'autoGenerateSKU',
            type: 'boolean',
            label: 'Auto-generate SKU',
            description: 'Automatically generate SKU codes for new items',
            required: false,
            default: true,
          },
          {
            key: 'skuFormat',
            type: 'text',
            label: 'SKU Format',
            description: 'Format for auto-generated SKUs (use {{category}} {{number}})',
            required: false,
            default: 'SKU-{{category}}-{{number}}',
            visibleIf: { trackSerialNumbers: true },
          },
          {
            key: 'lowStockAlert',
            type: 'number',
            label: 'Low Stock Alert (%)',
            description: 'Alert when stock falls below this percentage of reorder point',
            required: false,
            default: 20,
            min: 0,
            max: 100,
          },
        ],
      },
      {
        name: 'valuation',
        label: 'Inventory Valuation',
        icon: 'dollar-sign',
        order: 2,
        settings: [
          {
            key: 'valuationMethod',
            type: 'select',
            label: 'Valuation Method',
            description: 'Method for calculating inventory value',
            required: true,
            options: [
              { value: 'fifo', label: 'FIFO (First In, First Out)' },
              { value: 'lifo', label: 'LIFO (Last In, First Out)' },
              { value: 'average', label: 'Average Cost' },
              { value: 'standard', label: 'Standard Cost' },
            ],
            default: 'fifo',
          },
          {
            key: 'includeOverhead',
            type: 'boolean',
            label: 'Include Overhead Costs',
            description: 'Include overhead costs in inventory valuation',
            required: false,
            default: false,
          },
          {
            key: 'revaluationFrequency',
            type: 'select',
            label: 'Revaluation Frequency',
            description: 'How often to revalue inventory',
            required: false,
            options: [
              { value: 'daily', label: 'Daily' },
              { value: 'weekly', label: 'Weekly' },
              { value: 'monthly', label: 'Monthly' },
              { value: 'quarterly', label: 'Quarterly' },
              { value: 'yearly', label: 'Yearly' },
            ],
            default: 'monthly',
          },
        ],
      },
      {
        name: 'purchase',
        label: 'Purchase Orders',
        icon: 'shopping-cart',
        order: 3,
        settings: [
          {
            key: 'autoPOApproval',
            type: 'boolean',
            label: 'Auto-approve POs',
            description: 'Automatically approve purchase orders below threshold',
            required: false,
            default: false,
          },
          {
            key: 'poApprovalThreshold',
            type: 'number',
            label: 'Approval Threshold',
            description: 'PO value threshold for requiring approval',
            required: false,
            default: 1000,
            min: 0,
            visibleIf: { autoPOApproval: true },
          },
          {
            key: 'defaultPOCurrency',
            type: 'select',
            label: 'Default Currency',
            description: 'Default currency for purchase orders',
            required: true,
            optionsSource: 'currencies',
            default: 'USD',
          },
          {
            key: 'poNumberPrefix',
            type: 'text',
            label: 'PO Number Prefix',
            description: 'Prefix for purchase order numbers',
            required: false,
            default: 'PO',
          },
          {
            key: 'poNumberDigits',
            type: 'number',
            label: 'PO Number Digits',
            description: 'Number of digits in PO number',
            required: false,
            default: 4,
            min: 2,
            max: 10,
          },
        ],
      },
      {
        name: 'integration',
        label: 'Integration Settings',
        icon: 'link',
        order: 4,
        settings: [
          {
            key: 'accountingIntegration',
            type: 'select',
            label: 'Accounting Integration',
            description: 'Accounting system to sync with',
            required: false,
            options: [
              { value: 'none', label: 'None' },
              { value: 'quickbooks', label: 'QuickBooks' },
              { value: 'xero', label: 'Xero' },
              { value: 'sage', label: 'Sage' },
            ],
            default: 'none',
          },
          {
            key: 'syncInventoryValue',
            type: 'boolean',
            label: 'Sync Inventory Value',
            description: 'Sync inventory value to accounting system',
            required: false,
            default: false,
            visibleIf: { accountingIntegration: ['quickbooks', 'xero', 'sage'] },
          },
          {
            key: 'barcodeScanner',
            type: 'select',
            label: 'Barcode Scanner Type',
            description: 'Type of barcode scanner integration',
            required: false,
            options: [
              { value: 'none', label: 'None' },
              { value: 'keyboard', label: 'Keyboard Wedge' },
              { value: 'usb', label: 'USB Scanner' },
              { value: 'camera', label: 'Camera Scanner' },
            ],
            default: 'keyboard',
          },
        ],
      },
      {
        name: 'notifications',
        label: 'Notifications',
        icon: 'bell',
        order: 5,
        settings: [
          {
            key: 'lowStockAlerts',
            type: 'boolean',
            label: 'Low Stock Alerts',
            description: 'Send alerts for low stock levels',
            required: false,
            default: true,
          },
          {
            key: 'poStatusUpdates',
            type: 'boolean',
            label: 'PO Status Updates',
            description: 'Notify on PO status changes',
            required: false,
            default: true,
          },
          {
            key: 'stockMovementAlerts',
            type: 'boolean',
            label: 'Stock Movement Alerts',
            description: 'Alert on significant stock movements',
            required: false,
            default: false,
          },
          {
            key: 'expiryAlerts',
            type: 'boolean',
            label: 'Expiry Alerts',
            description: 'Alert for items approaching expiry',
            required: false,
            default: true,
          },
          {
            key: 'expiryDays',
            type: 'number',
            label: 'Expiry Alert Days',
            description: 'Days before expiry to send alert',
            required: false,
            default: 30,
            min: 1,
            max: 365,
            visibleIf: { expiryAlerts: true },
          },
        ],
      },
    ],
  },

  // Module features
  features: [
    {
      name: 'Multi-Warehouse',
      description: 'Manage inventory across multiple warehouses',
      icon: 'building-2',
    },
    {
      name: 'Batch & Serial Tracking',
      description: 'Track items by batch numbers and serial numbers',
      icon: 'hash',
    },
    {
      name: 'Barcode Scanning',
      description: 'Integrate barcode scanners for quick operations',
      icon: 'scan-line',
    },
    {
      name: 'Stock Forecasting',
      description: 'AI-powered stock forecasting and optimization',
      icon: 'trending-up',
    },
    {
      name: 'Auto-Reordering',
      description: 'Automatic reorder point calculations and PO creation',
      icon: 'refresh-cw',
    },
    {
      name: 'Supplier Management',
      description: 'Complete supplier relationship management',
      icon: 'users',
    },
    {
      name: 'Inventory Valuation',
      description: 'Multiple valuation methods (FIFO, LIFO, Average)',
      icon: 'calculator',
    },
    {
      name: 'Stock Adjustments',
      description: 'Manual adjustments with approval workflow',
      icon: 'edit-3',
    },
  ],

  // Export configuration
  export: {
    formats: ['pdf', 'excel', 'csv'],
    templates: {
      purchaseOrder: 'Purchase Order Template',
      stockReport: 'Stock Level Report',
      inventoryValuation: 'Inventory Valuation Report',
      supplierList: 'Supplier List',
    },
  },

  // Component mapping
  components: {
    main: 'InventoryPage',
    pages: {
      items: 'ItemsPage',
      stock: 'StockPage',
      warehouses: 'WarehousesPage',
      purchaseOrders: 'PurchaseOrdersPage',
      suppliers: 'SuppliersPage',
      adjustments: 'AdjustmentsPage',
      transfers: 'TransfersPage',
      reports: 'InventoryReportsPage',
    },
    modals: {
      itemForm: 'ItemFormModal',
      stockAdjustment: 'StockAdjustmentModal',
      transferForm: 'TransferFormModal',
      poForm: 'PurchaseOrderFormModal',
      supplierForm: 'SupplierFormModal',
    },
    widgets: {
      stockLevels: 'StockLevelsWidget',
      lowStock: 'LowStockWidget',
      recentMovements: 'RecentMovementsWidget',
      pendingPOs: 'PendingPOsWidget',
    },
  },
});

export default inventoryConfig;