import { useState } from "react";
import { Bot, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Card } from "@/components/ui/card";

interface AIDetailViewProps {
  chatId?: string;
}

const mockAIConversations = {
  '1': {
    title: 'Recipe for Pasta Carbonara',
    topic: 'Cooking',
    messages: [
      { id: '1', text: 'Can you give me a recipe for pasta carbonara?', sender: 'user', timestamp: '2:25 PM' },
      { id: '2', text: 'Here\'s a classic carbonara recipe:\n\nIngredients:\n- 400g spaghetti\n- 200g pancetta or guanciale\n- 4 large eggs\n- 100g Pecorino Romano cheese\n- Black pepper\n- Salt', sender: 'ai', timestamp: '2:26 PM' },
      { id: '3', text: 'How long should I cook the pasta?', sender: 'user', timestamp: '2:28 PM' },
      { id: '4', text: 'Cook the spaghetti in salted boiling water for about 8-10 minutes until al dente. The exact time depends on the brand, so check the package instructions.', sender: 'ai', timestamp: '2:29 PM' },
    ]
  },
  '2': {
    title: 'JavaScript Array Methods',
    topic: 'Programming',
    messages: [
      { id: '1', text: 'What are the most useful JavaScript array methods?', sender: 'user', timestamp: '1:40 PM' },
      { id: '2', text: 'The most commonly used array methods are:\n\n1. **map()** - transforms each element\n2. **filter()** - filters elements based on condition\n3. **reduce()** - reduces array to single value\n4. **forEach()** - executes function for each element\n5. **find()** - finds first matching element\n6. **some()** - tests if any element passes test\n7. **every()** - tests if all elements pass test', sender: 'ai', timestamp: '1:41 PM' },
    ]
  }
};

export function AIDetailView({ chatId }: AIDetailViewProps) {
  const [message, setMessage] = useState("");

  if (!chatId) {
    return (
      <div className="flex-1 flex items-center justify-center bg-background">
        <div className="text-center max-w-md">
          <div className="h-64 w-64 mx-auto mb-8 bg-gradient-to-br from-blue-600 to-purple-600 rounded-full flex items-center justify-center">
            <Bot className="h-24 w-24 text-white" />
          </div>
          <h2 className="text-xl font-semibold text-foreground mb-2">Ask Meta AI anything</h2>
          <p className="text-muted-foreground mb-6">
            Get help with writing, learning, brainstorming and more. Meta AI is built with Llama.
          </p>
          <div className="text-xs text-muted-foreground">
            Messages are generated by Meta AI. Some may be inaccurate or inappropriate.
            You can improve the quality by sending feedback.
          </div>
        </div>
      </div>
    );
  }

  const conversation = mockAIConversations[chatId as keyof typeof mockAIConversations];
  if (!conversation) return null;

  const handleSendMessage = () => {
    if (message.trim()) {
      console.log('Sending AI message:', message);
      setMessage("");
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <div className="flex-1 flex flex-col bg-background">
      {/* Header */}
      <div className="p-4 border-b border-border bg-card">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-full bg-gradient-to-br from-blue-600 to-purple-600 flex items-center justify-center">
            <Bot className="h-5 w-5 text-white" />
          </div>
          <div>
            <h3 className="font-medium text-foreground">{conversation.title}</h3>
            <p className="text-sm text-muted-foreground">Topic: {conversation.topic}</p>
          </div>
        </div>
      </div>

      {/* Messages */}
      <ScrollArea className="flex-1 p-4">
        <div className="space-y-4 max-w-4xl mx-auto">
          {conversation.messages.map((msg) => (
            <div key={msg.id} className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
              <Card className={`max-w-[80%] p-3 ${
                msg.sender === 'user' 
                  ? 'bg-primary text-primary-foreground' 
                  : 'bg-muted'
              }`}>
                <div className="whitespace-pre-wrap">{msg.text}</div>
                <div className={`text-xs mt-2 ${
                  msg.sender === 'user' 
                    ? 'text-primary-foreground/70' 
                    : 'text-muted-foreground'
                }`}>
                  {msg.timestamp}
                </div>
              </Card>
            </div>
          ))}
        </div>
      </ScrollArea>

      {/* Input */}
      <div className="p-4 border-t border-border bg-card">
        <div className="flex gap-2 max-w-4xl mx-auto">
          <Input
            placeholder="Ask Meta AI anything..."
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            onKeyPress={handleKeyPress}
            className="flex-1"
          />
          <Button onClick={handleSendMessage} disabled={!message.trim()}>
            <Send className="h-4 w-4" />
          </Button>
        </div>
      </div>
    </div>
  );
}
