import { useState } from "react";
import { Bot, Send, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Card } from "@/components/ui/card";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";

interface AIDetailViewProps {
  chatId?: string;
}

// Hook to fetch a single AI chat session from Convex
const useAIConversation = (chatId?: string) => {
  const session = useQuery(
    api.features.ai.queries.getChatSession,
    chatId ? { sessionId: chatId as Id<"aiChatSessions"> } : "skip"
  );

  const messages = (session?.messages ?? []).map((msg, idx) => ({
    id: `${chatId}-${idx}`,
    sender: msg.role === "user" ? "user" : "assistant",
    text: msg.content,
    timestamp: new Date(msg.timestamp).toLocaleTimeString(),
  }));

  return {
    conversation: session ? { title: session.title, topic: session.status } : null,
    messages,
    isLoading: chatId !== undefined && session === undefined,
  };
};

export function AIDetailView({ chatId }: AIDetailViewProps) {
  const [message, setMessage] = useState("");
  const { conversation, messages, isLoading } = useAIConversation(chatId);

  // Empty state - no conversation selected or no chatId
  if (!chatId) {
    return (
      <div className="flex-1 flex items-center justify-center bg-background">
        <div className="text-center max-w-md">
          <div className="h-64 w-64 mx-auto mb-8 bg-gradient-to-br from-blue-600 to-purple-600 rounded-full flex items-center justify-center">
            <Bot className="h-24 w-24 text-white" />
          </div>
          <h2 className="text-xl font-semibold text-foreground mb-2">Ask AI anything</h2>
          <p className="text-muted-foreground mb-6">
            Get help with writing, learning, brainstorming and more. AI is built with Llama.
          </p>
          <div className="text-xs text-muted-foreground">
            Messages are generated by AI. Some may be inaccurate or inappropriate.
            You can improve the quality by sending feedback.
          </div>
        </div>
      </div>
    );
  }

  // Loading state
  if (isLoading) {
    return (
      <div className="flex-1 flex items-center justify-center bg-background">
        <div className="animate-pulse text-muted-foreground">Loading conversation...</div>
      </div>
    );
  }

  // No messages yet - new conversation
  if (!messages || messages.length === 0) {
    return (
      <div className="flex-1 flex flex-col bg-background">
        {/* Header */}
        <div className="p-4 border-b border-border bg-card">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-gradient-to-br from-blue-600 to-purple-600 flex items-center justify-center">
              <Bot className="h-5 w-5 text-white" />
            </div>
            <div>
              <h3 className="font-medium text-foreground">New Conversation</h3>
              <p className="text-sm text-muted-foreground">Ask me anything</p>
            </div>
          </div>
        </div>

        {/* Empty conversation area */}
        <div className="flex-1 flex items-center justify-center p-4">
          <div className="text-center max-w-md">
            <Sparkles className="h-12 w-12 mx-auto mb-4 text-primary" />
            <h3 className="font-medium text-foreground mb-2">Start the conversation</h3>
            <p className="text-sm text-muted-foreground">
              Type a message below to begin chatting with AI.
            </p>
          </div>
        </div>

        {/* Input */}
        <div className="p-4 border-t border-border bg-card">
          <div className="flex gap-2 max-w-4xl mx-auto">
            <Input
              placeholder="Ask AI anything..."
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              onKeyPress={(e) => {
                if (e.key === 'Enter' && !e.shiftKey && message.trim()) {
                  e.preventDefault();
                  console.log('Sending AI message:', message);
                  setMessage("");
                }
              }}
              className="flex-1"
            />
            <Button disabled={!message.trim()}>
              <Send className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>
    );
  }

  const handleSendMessage = () => {
    if (message.trim()) {
      console.log('Sending AI message:', message);
      setMessage("");
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <div className="flex-1 flex flex-col bg-background">
      {/* Header */}
      <div className="p-4 border-b border-border bg-card">
        <div className="flex items-center gap-3">
          <div className="h-10 w-10 rounded-full bg-gradient-to-br from-blue-600 to-purple-600 flex items-center justify-center">
            <Bot className="h-5 w-5 text-white" />
          </div>
          <div>
            <h3 className="font-medium text-foreground">{conversation?.title || 'AI Chat'}</h3>
            <p className="text-sm text-muted-foreground">Topic: {conversation?.topic || 'General'}</p>
          </div>
        </div>
      </div>

      {/* Messages */}
      <ScrollArea className="flex-1 p-4">
        <div className="space-y-4 max-w-4xl mx-auto">
          {messages.map((msg: any) => (
            <div key={msg.id} className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
              <Card className={`max-w-[80%] p-3 ${
                msg.sender === 'user' 
                  ? 'bg-primary text-primary-foreground' 
                  : 'bg-muted'
              }`}>
                <div className="whitespace-pre-wrap">{msg.text}</div>
                <div className={`text-xs mt-2 ${
                  msg.sender === 'user' 
                    ? 'text-primary-foreground/70' 
                    : 'text-muted-foreground'
                }`}>
                  {msg.timestamp}
                </div>
              </Card>
            </div>
          ))}
        </div>
      </ScrollArea>

      {/* Input */}
      <div className="p-4 border-t border-border bg-card">
        <div className="flex gap-2 max-w-4xl mx-auto">
          <Input
            placeholder="Ask AI anything..."
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            onKeyPress={handleKeyPress}
            className="flex-1"
          />
          <Button onClick={handleSendMessage} disabled={!message.trim()}>
            <Send className="h-4 w-4" />
          </Button>
        </div>
      </div>
    </div>
  );
}
