/**
 * ERP CRM Module Configuration
 * Auto-discovered by the ERP system
 */

import { createModuleConfig } from '@/lib/module-config';
import type { ModuleConfig } from '@/types/module';

const crmConfig: ModuleConfig = createModuleConfig({
  // Module metadata
  name: 'crm',
  displayName: 'CRM & Sales',
  description: 'Customer relationship management and sales automation',
  version: '1.0.0',
  category: 'erp',

  // Module icon and visual
  icon: 'users',
  emoji: '👥',
  color: 'blue',

  // Route configuration
  route: '/erp/crm',

  // Module type
  moduleType: 'feature',
  hasUI: true,
  hasConvex: true,
  hasTests: false,
  hasSettings: true,

  // Module status
  state: 'active',
  isReady: true,
  isCore: true,

  // Module order
  order: 30,

  // Dependencies
  dependsOn: ['workspaces', 'users', 'shared-search', 'shared-activity', 'shared-comments'],

  // Features provided
  provides: [
    'contacts',
    'leads',
    'opportunities',
    'accounts',
    'campaigns',
    'sales-automation',
    'email-tracking',
    'deal-management',
    'sales-reports',
    'customer-support',
    'lead-scoring',
  ],

  // Sub-modules
  subModules: [
    {
      id: 'contacts',
      name: 'contacts',
      displayName: 'Contacts',
      description: 'Manage customer and contact information',
      icon: 'user',
      route: '/erp/crm/contacts',
      component: 'ContactsPage',
      order: 1,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40],
        update: [10, 20, 30],
        delete: [10, 20],
        export: [10, 20, 30, 40],
        import: [10, 20, 30],
      },
    },
    {
      id: 'leads',
      name: 'leads',
      displayName: 'Leads',
      description: 'Track and manage sales leads',
      icon: 'target',
      route: '/erp/crm/leads',
      component: 'LeadsPage',
      order: 2,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40],
        update: [10, 20, 30],
        delete: [10, 20],
        convert: [10, 20, 30, 40],
        assign: [10, 20, 30, 40],
      },
    },
    {
      id: 'opportunities',
      name: 'opportunities',
      displayName: 'Opportunities',
      description: 'Manage sales opportunities and deals',
      icon: 'trending-up',
      route: '/erp/crm/opportunities',
      component: 'OpportunitiesPage',
      order: 3,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40],
        update: [10, 20, 30],
        delete: [10, 20],
        close: [10, 20, 30],
        stage: [10, 20, 30, 40],
      },
    },
    {
      id: 'accounts',
      name: 'accounts',
      displayName: 'Accounts',
      description: 'Manage customer accounts and companies',
      icon: 'building',
      route: '/erp/crm/accounts',
      component: 'AccountsPage',
      order: 4,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40],
        update: [10, 20, 30],
        delete: [10, 20],
        merge: [10, 20, 30],
      },
    },
    {
      id: 'campaigns',
      name: 'campaigns',
      displayName: 'Campaigns',
      description: 'Create and manage marketing campaigns',
      icon: 'megaphone',
      route: '/erp/crm/campaigns',
      component: 'CampaignsPage',
      order: 5,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40],
        update: [10, 20, 30],
        delete: [10, 20],
        launch: [10, 20, 30],
        pause: [10, 20, 30],
      },
    },
    {
      id: 'activities',
      name: 'activities',
      displayName: 'Activities',
      description: 'Track all CRM activities and interactions',
      icon: 'activity',
      route: '/erp/crm/activities',
      component: 'ActivitiesPage',
      order: 6,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40, 50],
        update: [10, 20, 30, 40],
        delete: [10, 20, 30],
        complete: [10, 20, 30, 40, 50],
      },
    },
    {
      id: 'tasks',
      name: 'tasks',
      displayName: 'Tasks',
      description: 'Manage sales tasks and follow-ups',
      icon: 'check-square',
      route: '/erp/crm/tasks',
      component: 'CrmTasksPage',
      order: 7,
      permissions: {
        read: [10, 20, 30, 40, 50],
        create: [10, 20, 30, 40, 50],
        update: [10, 20, 30, 40, 50],
        delete: [10, 20, 30],
        complete: [10, 20, 30, 40, 50],
        assign: [10, 20, 30, 40],
      },
    },
    {
      id: 'reports',
      name: 'reports',
      displayName: 'Reports & Analytics',
      description: 'CRM reports and sales analytics',
      icon: 'bar-chart',
      route: '/erp/crm/reports',
      component: 'CrmReportsPage',
      order: 8,
      permissions: {
        read: [10, 20, 30, 40, 50],
        export: [10, 20, 30, 40],
      },
    },
    {
      id: 'automation',
      name: 'automation',
      displayName: 'Automation',
      description: 'Configure sales automation rules',
      icon: 'zap',
      route: '/erp/crm/automation',
      component: 'CrmAutomationPage',
      order: 9,
      permissions: {
        read: [10, 20, 30],
        create: [10, 20],
        update: [10, 20],
        delete: [10, 20],
        activate: [10, 20],
      },
    },
  ],

  // API endpoints
  api: {
    base: '/api/erp/crm',
    endpoints: {
      contacts: {
        list: 'GET /contacts',
        get: 'GET /contacts/:id',
        create: 'POST /contacts',
        update: 'PUT /contacts/:id',
        delete: 'DELETE /contacts/:id',
        convert: 'POST /contacts/:id/convert',
        merge: 'POST /contacts/merge',
        duplicate: 'POST /contacts/:id/duplicate',
        tags: 'GET /contacts/tags',
      },
      leads: {
        list: 'GET /leads',
        get: 'GET /leads/:id',
        create: 'POST /leads',
        update: 'PUT /leads/:id',
        delete: 'DELETE /leads/:id',
        convert: 'POST /leads/:id/convert',
        assign: 'POST /leads/:id/assign',
        score: 'GET /leads/:id/score',
        activities: 'GET /leads/:id/activities',
      },
      opportunities: {
        list: 'GET /opportunities',
        get: 'GET /opportunities/:id',
        create: 'POST /opportunities',
        update: 'PUT /opportunities/:id',
        delete: 'DELETE /opportunities/:id',
        close: 'POST /opportunities/:id/close',
        moveStage: 'POST /opportunities/:id/stage',
        probability: 'GET /opportunities/probability',
        forecast: 'GET /opportunities/forecast',
      },
      accounts: {
        list: 'GET /accounts',
        get: 'GET /accounts/:id',
        create: 'POST /accounts',
        update: 'PUT /accounts/:id',
        delete: 'DELETE /accounts/:id',
        merge: 'POST /accounts/merge',
        contacts: 'GET /accounts/:id/contacts',
        opportunities: 'GET /accounts/:id/opportunities',
        value: 'GET /accounts/:id/value',
      },
      campaigns: {
        list: 'GET /campaigns',
        get: 'GET /campaigns/:id',
        create: 'POST /campaigns',
        update: 'PUT /campaigns/:id',
        delete: 'DELETE /campaigns/:id',
        launch: 'POST /campaigns/:id/launch',
        pause: 'POST /campaigns/:id/pause',
        stats: 'GET /campaigns/:id/stats',
        leads: 'GET /campaigns/:id/leads',
      },
      activities: {
        list: 'GET /activities',
        get: 'GET /activities/:id',
        create: 'POST /activities',
        update: 'PUT /activities/:id',
        delete: 'DELETE /activities/:id',
        complete: 'POST /activities/:id/complete',
        calendar: 'GET /activities/calendar',
        upcoming: 'GET /activities/upcoming',
      },
      tasks: {
        list: 'GET /tasks',
        get: 'GET /tasks/:id',
        create: 'POST /tasks',
        update: 'PUT /tasks/:id',
        delete: 'DELETE /tasks/:id',
        complete: 'POST /tasks/:id/complete',
        assign: 'POST /tasks/:id/assign',
        myTasks: 'GET /tasks/my',
        overdue: 'GET /tasks/overdue',
      },
      email: {
        send: 'POST /email/send',
        templates: 'GET /email/templates',
        template: 'GET /email/templates/:id',
        track: 'POST /email/track',
        reply: 'POST /email/reply',
        signature: 'GET /email/signature',
      },
      reports: {
        sales: 'GET /reports/sales',
        pipeline: 'GET /reports/pipeline',
        conversion: 'GET /reports/conversion',
        activities: 'GET /reports/activities',
        performance: 'GET /reports/performance',
        forecast: 'GET /reports/forecast',
        export: 'POST /reports/export',
      },
      automation: {
        rules: 'GET /automation/rules',
        createRule: 'POST /automation/rules',
        updateRule: 'PUT /automation/rules/:id',
        deleteRule: 'DELETE /automation/rules/:id',
        activate: 'POST /automation/rules/:id/activate',
        logs: 'GET /automation/logs',
      },
    },
  },

  // Database tables
  tables: [
    // Core tables
    'contacts',
    'leadSources',
    'leads',
    'opportunities',
    'opportunityStages',
    'accounts',
    'accountTypes',
    'campaigns',
    'campaignTypes',
    'activities',
    'activityTypes',
    'tasks',
    'taskTypes',

    // Supporting tables
    'contactRelations',
    'accountContacts',
    'opportunityContacts',
    'accountOwners',
    'campaignMembers',
    'emailTemplates',
    'emailTracking',
    'customFields',
    'tags',
    'notes',
    'attachments',
    'automationRules',
    'webhooks',

    // Analytics tables
    'salesForecasts',
    'conversionMetrics',
    'activityMetrics',
    'performanceMetrics',
  ],

  // Settings configuration
  settings: {
    groups: [
      {
        name: 'general',
        label: 'General Settings',
        icon: 'settings',
        order: 1,
        settings: [
          {
            key: 'defaultAssignee',
            type: 'select',
            label: 'Default Assignee',
            description: 'Default user for new leads and opportunities',
            required: false,
            optionsSource: 'users',
          },
          {
            key: 'timeZone',
            type: 'select',
            label: 'Time Zone',
            description: 'Time zone for activity scheduling',
            required: true,
            options: [
              { value: 'UTC', label: 'UTC' },
              { value: 'America/New_York', label: 'Eastern Time' },
              { value: 'America/Chicago', label: 'Central Time' },
              { value: 'America/Denver', label: 'Mountain Time' },
              { value: 'America/Los_Angeles', label: 'Pacific Time' },
            ],
            default: 'UTC',
          },
          {
            key: 'dateFormat',
            type: 'select',
            label: 'Date Format',
            description: 'Display format for dates',
            required: true,
            options: [
              { value: 'MM/DD/YYYY', label: 'MM/DD/YYYY' },
              { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY' },
              { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD' },
            ],
            default: 'MM/DD/YYYY',
          },
          {
            key: 'currency',
            type: 'select',
            label: 'Default Currency',
            description: 'Currency for opportunity values',
            required: true,
            optionsSource: 'currencies',
            default: 'USD',
          },
        ],
      },
      {
        name: 'leads',
        label: 'Lead Management',
        icon: 'target',
        order: 2,
        settings: [
          {
            key: 'autoAssignLeads',
            type: 'boolean',
            label: 'Auto-assign Leads',
            description: 'Automatically assign new leads to users',
            required: false,
            default: true,
          },
          {
            key: 'leadAssignmentRule',
            type: 'select',
            label: 'Assignment Rule',
            description: 'How to assign leads',
            required: false,
            options: [
              { value: 'round-robin', label: 'Round Robin' },
              { value: 'territory', label: 'By Territory' },
              { value: 'workload', label: 'By Workload' },
              { value: 'random', label: 'Random' },
            ],
            default: 'round-robin',
            visibleIf: { autoAssignLeads: true },
          },
          {
            key: 'leadScoreEnabled',
            type: 'boolean',
            label: 'Enable Lead Scoring',
            description: 'Automatically score leads based on criteria',
            required: false,
            default: true,
          },
          {
            key: 'leadScoreModel',
            type: 'select',
            label: 'Scoring Model',
            description: 'Lead scoring algorithm',
            required: false,
            options: [
              { value: 'simple', label: 'Simple Points' },
              { value: 'weighted', label: 'Weighted Criteria' },
              { value: 'ml', label: 'Machine Learning' },
            ],
            default: 'simple',
            visibleIf: { leadScoreEnabled: true },
          },
          {
            key: 'leadDuplicationsCheck',
            type: 'boolean',
            label: 'Check for Duplicates',
            description: 'Identify potential duplicate leads',
            required: false,
            default: true,
          },
        ],
      },
      {
        name: 'opportunities',
        label: 'Opportunity Settings',
        icon: 'trending-up',
        order: 3,
        settings: [
          {
            key: 'defaultStage',
            type: 'select',
            label: 'Default Stage',
            description: 'Initial stage for new opportunities',
            required: false,
            optionsSource: 'opportunityStages',
          },
          {
            key: 'autoCalculateProbability',
            type: 'boolean',
            label: 'Auto-calculate Probability',
            description: 'Automatically calculate win probability',
            required: false,
            default: true,
          },
          {
            key: 'forecastMethod',
            type: 'select',
            label: 'Forecast Method',
            description: 'Method for sales forecasting',
            required: true,
            options: [
              { value: 'standard', label: 'Standard (Amount × Probability)' },
              { value: 'weighted', label: 'Weighted by Stage' },
              { value: 'ml', label: 'Machine Learning' },
            ],
            default: 'standard',
          },
          {
            key: 'closeDealAlert',
            type: 'number',
            label: 'Close Deal Alert (days)',
            description: 'Alert before deal close date',
            required: false,
            default: 7,
            min: 1,
            max: 30,
          },
        ],
      },
      {
        name: 'email',
        label: 'Email Integration',
        icon: 'mail',
        order: 4,
        settings: [
          {
            key: 'emailIntegration',
            type: 'select',
            label: 'Email Provider',
            description: 'Email service provider',
            required: false,
            options: [
              { value: 'none', label: 'None' },
              { value: 'smtp', label: 'SMTP Server' },
              { value: 'sendgrid', label: 'SendGrid' },
              { value: 'ses', label: 'Amazon SES' },
              { value: 'gmail', label: 'Gmail API' },
              { value: 'outlook', label: 'Outlook API' },
            ],
            default: 'none',
          },
          {
            key: 'emailSync',
            type: 'boolean',
            label: 'Sync Emails',
            description: 'Sync emails with contacts',
            required: false,
            default: false,
            visibleIf: { emailIntegration: ['gmail', 'outlook'] },
          },
          {
            key: 'emailTracking',
            type: 'boolean',
            label: 'Track Email Opens',
            description: 'Track when emails are opened',
            required: false,
            default: true,
          },
          {
            key: 'emailTemplates',
            type: 'boolean',
            label: 'Use Email Templates',
            description: 'Enable email template library',
            required: false,
            default: true,
          },
        ],
      },
      {
        name: 'automation',
        label: 'Automation Rules',
        icon: 'zap',
        order: 5,
        settings: [
          {
            key: 'automationEnabled',
            type: 'boolean',
            label: 'Enable Automation',
            description: 'Enable workflow automation',
            required: false,
            default: true,
          },
          {
            key: 'autoCreateTasks',
            type: 'boolean',
            label: 'Auto-create Follow-up Tasks',
            description: 'Create follow-up tasks automatically',
            required: false,
            default: true,
          },
          {
            key: 'autoNotify',
            type: 'boolean',
            label: 'Auto-notify Assignees',
            description: 'Notify users on assignment',
            required: false,
            default: true,
          },
          {
            key: 'leadNurturing',
            type: 'boolean',
            label: 'Lead Nurturing',
            description: 'Automated lead nurturing campaigns',
            required: false,
            default: false,
          },
          {
            key: 'duplicatesMerge',
            type: 'select',
            label: 'Duplicate Handling',
            description: 'How to handle duplicate records',
            required: false,
            options: [
              { value: 'alert', label: 'Alert Only' },
              { value: 'merge', label: 'Auto-merge' },
              { value: 'skip', label: 'Skip Creation' },
            ],
            default: 'alert',
          },
        ],
      },
      {
        name: 'privacy',
        label: 'Privacy & Compliance',
        icon: 'shield',
        order: 6,
        settings: [
          {
            key: 'gdprCompliance',
            type: 'boolean',
            label: 'GDPR Compliance',
            description: 'Enable GDPR compliance features',
            required: false,
            default: false,
          },
          {
            key: 'dataRetention',
            type: 'number',
            label: 'Data Retention (days)',
            description: 'Days to keep deleted data',
            required: false,
            default: 365,
            min: 30,
            max: 2555,
          },
          {
            key: 'anonymizeAfter',
            type: 'number',
            label: 'Anonymize After (days)',
            description: 'Days to anonymize inactive contacts',
            required: false,
            default: 1095,
            min: 365,
            max: 3650,
          },
          {
            key: 'emailConsent',
            type: 'boolean',
            label: 'Require Email Consent',
            description: 'Require consent for marketing emails',
            required: false,
            default: true,
          },
        ],
      },
    ],
  },

  // Module features
  features: [
    {
      name: 'Lead Scoring',
      description: 'Automatic lead scoring based on behavior and demographics',
      icon: 'star',
    },
    {
      name: 'Sales Pipeline',
      description: 'Visual sales pipeline management',
      icon: 'git-branch',
    },
    {
      name: 'Email Integration',
      description: 'Sync emails and track interactions',
      icon: 'mail',
    },
    {
      name: 'Campaign Management',
      description: 'Create and track marketing campaigns',
      icon: 'megaphone',
    },
    {
      name: 'Activity Tracking',
      description: 'Track all customer interactions',
      icon: 'activity',
    },
    {
      name: 'Sales Forecasting',
      description: 'AI-powered sales forecasting',
      icon: 'trending-up',
    },
    {
      name: 'Automation',
      description: 'Automate routine sales tasks',
      icon: 'zap',
    },
    {
      name: 'Mobile App',
      description: 'Full-featured mobile CRM app',
      icon: 'smartphone',
    },
  ],

  // Export configuration
  export: {
    formats: ['pdf', 'excel', 'csv'],
    templates: {
      contactList: 'Contact List',
      leadReport: 'Lead Report',
      pipeline: 'Sales Pipeline',
      forecast: 'Sales Forecast',
      activities: 'Activity Report',
    },
  },

  // Component mapping
  components: {
    main: 'CrmPage',
    pages: {
      contacts: 'ContactsPage',
      leads: 'LeadsPage',
      opportunities: 'OpportunitiesPage',
      accounts: 'AccountsPage',
      campaigns: 'CampaignsPage',
      activities: 'ActivitiesPage',
      tasks: 'CrmTasksPage',
      reports: 'CrmReportsPage',
      automation: 'CrmAutomationPage',
    },
    modals: {
      contactForm: 'ContactFormModal',
      leadForm: 'LeadFormModal',
      opportunityForm: 'OpportunityFormModal',
      accountForm: 'AccountFormModal',
      campaignForm: 'CampaignFormModal',
      activityForm: 'ActivityFormModal',
      taskForm: 'CrmTaskFormModal',
    },
    widgets: {
      pipeline: 'PipelineWidget',
      salesMetrics: 'SalesMetricsWidget',
      recentActivities: 'RecentActivitiesWidget',
      upcomingTasks: 'UpcomingTasksWidget',
      leadConversion: 'LeadConversionWidget',
    },
  },
});

export default crmConfig;