/**
 * ERP Sales Module Configuration
 *
 * Complete sales management with quotes, invoices, payments, and analytics
 */

import { defineFeature } from "@/lib/features/defineFeature"

export default defineFeature({
  id: 'erp-sales',
  name: 'Sales & Invoicing',
  description: 'Complete sales management solution with quotes, invoices, recurring billing, payment processing, and sales analytics',

  ui: {
    icon: 'ShoppingCart',
    path: '/dashboard/erp/sales',
    component: 'SalesPage',
    category: 'erp',
    order: 100,
    group: 'ERP Suite',
    color: '#3B82F6',
    beta: false,
    featured: true,
  },

  technical: {
    featureType: 'optional',
    hasUI: true,
    hasConvex: true,
    hasTests: true,
    version: '1.0.0',
    dependencies: ['erp-crm', 'erp-inventory', 'users', 'notifications'],
    bundleId: 'business-pro',
  },

  status: {
    state: 'stable',
    isReady: true,
    lastUpdated: new Date('2025-01-20'),
  },

  permissions: [
    'erp.sales.view',
    'erp.sales.create',
    'erp.sales.edit',
    'erp.sales.delete',
    'erp.sales.approve',
    'erp.sales.export',
    'erp.sales.quotations.view',
    'erp.sales.quotations.create',
    'erp.sales.quotations.edit',
    'erp.sales.quotations.delete',
    'erp.sales.quotations.approve',
    'erp.sales.quotations.convert',
    'erp.sales.invoices.view',
    'erp.sales.invoices.create',
    'erp.sales.invoices.edit',
    'erp.sales.invoices.delete',
    'erp.sales.invoices.approve',
    'erp.sales.invoices.send',
    'erp.sales.invoices.pay',
    'erp.sales.recurring.view',
    'erp.sales.recurring.create',
    'erp.sales.recurring.edit',
    'erp.sales.recurring.pause',
    'erp.sales.recurring.cancel',
    'erp.sales.payments.view',
    'erp.sales.payments.create',
    'erp.sales.payments.refund',
    'erp.sales.credits.view',
    'erp.sales.credits.create',
    'erp.sales.credits.apply',
    'erp.sales.orders.view',
    'erp.sales.orders.create',
    'erp.sales.orders.edit',
    'erp.sales.orders.fulfill',
    'erp.sales.discounts.view',
    'erp.sales.discounts.create',
    'erp.sales.discounts.manage',
    'erp.sales.tax.view',
    'erp.sales.tax.manage',
    'erp.sales.reports.view',
    'erp.sales.reports.export',
    'erp.sales.analytics.view',
    'erp.sales.templates.manage',
    'erp.sales.email.manage',
  ],

  // Sub-modules (features)
  children: [
    {
      id: 'erp-sales-quotations',
      name: 'Quotations & Estimates',
      description: 'Create and manage price quotes with approval workflows',
      icon: 'FileText',
      path: '/dashboard/erp/sales/quotations',
      component: 'QuotationsPage',
      order: 10,
      permissions: [
        'erp.sales.quotations.view',
        'erp.sales.quotations.create',
        'erp.sales.quotations.edit',
        'erp.sales.quotations.delete',
        'erp.sales.quotations.approve',
        'erp.sales.quotations.convert',
      ],
    },
    {
      id: 'erp-sales-recurring',
      name: 'Recurring Invoices',
      description: 'Automated billing for subscriptions and recurring services',
      icon: 'Repeat',
      path: '/dashboard/erp/sales/recurring',
      component: 'RecurringInvoicesPage',
      order: 20,
      permissions: [
        'erp.sales.recurring.view',
        'erp.sales.recurring.create',
        'erp.sales.recurring.edit',
        'erp.sales.recurring.pause',
        'erp.sales.recurring.cancel',
      ],
    },
    {
      id: 'erp-sales-payments',
      name: 'Payment Processing',
      description: 'Multi-gateway payment processing and reconciliation',
      icon: 'CreditCard',
      path: '/dashboard/erp/sales/payments',
      component: 'PaymentsPage',
      order: 30,
      permissions: [
        'erp.sales.payments.view',
        'erp.sales.payments.create',
        'erp.sales.payments.refund',
      ],
    },
    {
      id: 'erp-sales-templates',
      name: 'Invoice Templates',
      description: 'Customizable invoice and quote templates',
      icon: 'Layout',
      path: '/dashboard/erp/sales/templates',
      component: 'TemplatesPage',
      order: 40,
      permissions: [
        'erp.sales.templates.manage',
      ],
    },
    {
      id: 'erp-sales-email',
      name: 'Email Automation',
      description: 'Automated invoice and reminder emails',
      icon: 'Mail',
      path: '/dashboard/erp/sales/email',
      component: 'EmailAutomationPage',
      order: 50,
      permissions: [
        'erp.sales.email.manage',
      ],
    },
    {
      id: 'erp-sales-credits',
      name: 'Credit Notes',
      description: 'Manage refunds and adjustments',
      icon: 'Receipt',
      path: '/dashboard/erp/sales/credits',
      component: 'CreditNotesPage',
      order: 60,
      permissions: [
        'erp.sales.credits.view',
        'erp.sales.credits.create',
        'erp.sales.credits.apply',
      ],
    },
    {
      id: 'erp-sales-currency',
      name: 'Multi-Currency',
      description: 'Multi-currency support and exchange rates',
      icon: 'DollarSign',
      path: '/dashboard/erp/sales/currency',
      component: 'CurrencyPage',
      order: 70,
      permissions: [
        'erp.sales.currency.view',
        'erp.sales.currency.manage',
      ],
    },
    {
      id: 'erp-sales-plans',
      name: 'Payment Plans',
      description: 'Installment payment tracking and management',
      icon: 'Calendar',
      path: '/dashboard/erp/sales/plans',
      component: 'PaymentPlansPage',
      order: 80,
      permissions: [
        'erp.sales.plans.view',
        'erp.sales.plans.create',
        'erp.sales.plans.manage',
      ],
    },
    {
      id: 'erp-sales-orders',
      name: 'Sales Orders',
      description: 'Pre-invoice order management and fulfillment',
      icon: 'Package',
      path: '/dashboard/erp/sales/orders',
      component: 'SalesOrdersPage',
      order: 90,
      permissions: [
        'erp.sales.orders.view',
        'erp.sales.orders.create',
        'erp.sales.orders.edit',
        'erp.sales.orders.fulfill',
      ],
    },
    {
      id: 'erp-sales-discounts',
      name: 'Discount Management',
      description: 'Coupons, bulk discounts, and promotional pricing',
      icon: 'Tag',
      path: '/dashboard/erp/sales/discounts',
      component: 'DiscountsPage',
      order: 100,
      permissions: [
        'erp.sales.discounts.view',
        'erp.sales.discounts.create',
        'erp.sales.discounts.manage',
      ],
    },
    {
      id: 'erp-sales-tax',
      name: 'Tax Configuration',
      description: 'Multi-jurisdiction tax rates and exemptions',
      icon: 'Percent',
      path: '/dashboard/erp/sales/tax',
      component: 'TaxPage',
      order: 110,
      permissions: [
        'erp.sales.tax.view',
        'erp.sales.tax.manage',
      ],
    },
    {
      id: 'erp-sales-approval',
      name: 'Approval Workflow',
      description: 'Multi-level invoice approval workflows',
      icon: 'CheckCircle',
      path: '/dashboard/erp/sales/approval',
      component: 'ApprovalPage',
      order: 120,
      permissions: [
        'erp.sales.approve',
      ],
    },
    {
      id: 'erp-sales-analytics',
      name: 'Sales Analytics',
      description: 'Revenue trends, forecasting, and performance metrics',
      icon: 'BarChart3',
      path: '/dashboard/erp/sales/analytics',
      component: 'SalesAnalyticsPage',
      order: 130,
      permissions: [
        'erp.sales.analytics.view',
        'erp.sales.reports.view',
        'erp.sales.reports.export',
      ],
    },
  ],

  // Bundle membership
  bundleMembership: {
    core: ['business-pro', 'enterprise'],
    recommended: ['sales-crm'],
    optional: ['startup'],
  },

  // Settings configuration
  settings: {
    defaultCurrency: 'USD',
    autoNumbering: {
      quotes: true,
      invoices: true,
      creditNotes: true,
    },
    numberFormats: {
      quote: 'Q-{YYYY}-{MM}-{seq}',
      invoice: 'INV-{YYYY}-{MM}-{seq}',
      creditNote: 'CN-{YYYY}-{MM}-{seq}',
    },
    paymentGateways: ['stripe', 'paypal'],
    defaultTerms: 'Net 30',
    taxIncluded: false,
    allowPartialPayments: true,
    lateFee: {
      enabled: false,
      percentage: 5,
      days: 30,
    },
    emailTemplates: {
      quote: 'default',
      invoice: 'default',
      reminder: 'default',
      receipt: 'default',
    },
  },

  // API endpoints
  api: {
    base: '/api/erp/sales',
    endpoints: {
      quotes: '/quotes',
      invoices: '/invoices',
      payments: '/payments',
      recurring: '/recurring-invoices',
      credits: '/credit-notes',
      orders: '/sales-orders',
      discounts: '/discounts',
      tax: '/tax',
      reports: '/reports',
      analytics: '/analytics',
    },
  },

  // Webhooks
  webhooks: {
    'quote.created': 'erp.sales.quotation.created',
    'quote.approved': 'erp.sales.quotation.approved',
    'quote.converted': 'erp.sales.quotation.converted',
    'invoice.created': 'erp.sales.invoice.created',
    'invoice.paid': 'erp.sales.invoice.paid',
    'invoice.overdue': 'erp.sales.invoice.overdue',
    'payment.received': 'erp.sales.payment.received',
    'payment.failed': 'erp.sales.payment.failed',
    'recurring.generated': 'erp.sales.recurring.generated',
    'credit.issued': 'erp.sales.credit.issued',
  },
})