// This is the single source of truth for default menu items.
// It is safe to import in Convex server functions.

export const DEFAULT_MENU_ITEMS = [
  {
    name: "Dashboard",
    slug: "dashboard",
    type: "route" as const,
    icon: "Home",
    path: "/dashboard",
    component: "OverviewPage",
    order: 1,
    metadata: { description: "Overview and analytics" },
  },
  {
    name: "WhatsApp",
    slug: "wa",
    type: "folder" as const,
    icon: "MessageCircle",
    path: "/wa",
    component: "WAPage",
    order: 3,
    metadata: { description: "WhatsApp Clone Features" },
    children: [
      {
        name: "Chats",
        slug: "wa-chats",
        type: "route" as const,
        icon: "MessageCircle",
        path: "/wa/chats",
        component: "WAChatsPage",
        order: 1,
        metadata: { description: "Chat conversations" },
      },
      {
        name: "Calls",
        slug: "wa-calls",
        type: "route" as const,
        icon: "Phone",
        path: "/wa/calls",
        component: "WACallsPage",
        order: 2,
        metadata: { description: "Voice and video calls" },
      },
      {
        name: "Status",
        slug: "wa-status",
        type: "route" as const,
        icon: "Camera",
        path: "/wa/status",
        component: "WAStatusPage",
        order: 3,
        metadata: { description: "Status updates" },
      },
      {
        name: "Meta AI",
        slug: "wa-ai",
        type: "route" as const,
        icon: "Bot",
        path: "/wa/ai",
        component: "WAAIPage",
        order: 4,
        metadata: { description: "AI assistant" },
      },
      {
        name: "Starred",
        slug: "wa-starred",
        type: "route" as const,
        icon: "Star",
        path: "/wa/starred",
        component: "WAStarredPage",
        order: 5,
        metadata: { description: "Starred messages" },
      },
      {
        name: "Archived",
        slug: "wa-archived",
        type: "route" as const,
        icon: "Archive",
        path: "/wa/archived",
        component: "WAArchivedPage",
        order: 6,
        metadata: { description: "Archived chats" },
      },
      {
        name: "Settings",
        slug: "wa-settings",
        type: "route" as const,
        icon: "Settings",
        path: "/wa/settings",
        component: "WASettingsPage",
        order: 7,
        metadata: { description: "WhatsApp settings" },
      },
      {
        name: "Profile",
        slug: "wa-profile",
        type: "route" as const,
        icon: "User",
        path: "/wa/profile",
        component: "WAProfilePage",
        order: 8,
        metadata: { description: "User profile" },
      },
    ],
  },
  {
    name: "Members",
    slug: "members",
    type: "route" as const,
    icon: "Users",
    path: "/members",
    component: "MembersPage",
    order: 4,
    metadata: { description: "Manage workspace members" },
    requiresPermission: "MANAGE_MEMBERS",
  },
  {
    name: "Friends",
    slug: "friends",
    type: "route" as const,
    icon: "Heart",
    path: "/friends",
    component: "FriendsPage",
    order: 5,
    metadata: { description: "Manage your friends" },
  },
  {
    name: "Documents",
    slug: "documents",
    type: "route" as const,
    icon: "FileText",
    path: "/documents",
    component: "DocumentsPage",
    order: 6,
    metadata: { description: "Collaborative documents" },
  },
  {
    name: "Canvas",
    slug: "canvas",
    type: "route" as const,
    icon: "Palette",
    path: "/canvas",
    component: "CanvasPage",
    order: 7,
    metadata: { description: "Visual collaboration" },
  },
  {
    name: "Menu Store",
    slug: "menus",
    type: "route" as const,
    icon: "Menu",
    path: "/menus",
    component: "MenusPage",
    order: 10,
    metadata: { description: "Manage navigation menus" },
    requiresPermission: "MANAGE_MENUS",
  },
  {
    name: "Invitations",
    slug: "invitations",
    type: "route" as const,
    icon: "Mail",
    path: "/invitations",
    component: "InvitationsPage",
    order: 11,
    metadata: { description: "Manage invitations" },
  },
  {
    name: "Profile",
    slug: "user-settings",
    type: "route" as const,
    icon: "User",
    path: "/user-settings",
    component: "ProfilePage",
    order: 20,
    metadata: { description: "Manage your profile" },
  },
  {
    name: "Settings",
    slug: "settings",
    type: "route" as const,
    icon: "Settings",
    path: "/settings",
    component: "WorkspacesPage",
    order: 99,
    metadata: { description: "Workspace configuration" },
    requiresPermission: "MANAGE_WORKSPACE",
  },
]
