/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/features/generate-registry.ts
 * Source of truth: frontend/features/[feature]/config.ts
 *
 * To update this file, modify feature config files and run:
 *   pnpm run sync:all
 */

import type { FeatureConfig } from './defineFeature'

import overviewConfig from '@/frontend/features/overview/config'
import communicationsConfig from '@/frontend/features/communications/config'
import statusConfig from '@/frontend/features/status/config'
import aiConfig from '@/frontend/features/ai/config'
import workspaceStoreConfig from '@/frontend/features/workspace-store/config'
import knowledgeConfig from '@/frontend/features/knowledge/config'
import contactConfig from '@/frontend/features/contact/config'
import databaseConfig from '@/frontend/features/database/config'
import documentsConfig from '@/frontend/features/documents/config'
import menuStoreConfig from '@/frontend/features/menu-store/config'
import calendarConfig from '@/frontend/features/calendar/config'
import userManagementConfig from '@/frontend/features/user-management/config'
import reportsConfig from '@/frontend/features/reports/config'
import tasksConfig from '@/frontend/features/tasks/config'
import formsConfig from '@/frontend/features/forms/config'
import approvalsConfig from '@/frontend/features/approvals/config'
import supportConfig from '@/frontend/features/support/config'
import projectsConfig from '@/frontend/features/projects/config'
import auditLogConfig from '@/frontend/features/audit-log/config'
import importExportConfig from '@/frontend/features/import-export/config'
import integrationsConfig from '@/frontend/features/integrations/config'
import posConfig from '@/frontend/features/pos/config'
import builderConfig from '@/frontend/features/builder/config'
import marketingConfig from '@/frontend/features/marketing/config'
import analyticsConfig from '@/frontend/features/analytics/config'
import biConfig from '@/frontend/features/bi/config'
import automationConfig from '@/frontend/features/automation/config'
import salesConfig from '@/frontend/features/sales/config'
import hrConfig from '@/frontend/features/hr/config'
import contentConfig from '@/frontend/features/content/config'
import cmsLiteConfig from '@/frontend/features/cms-lite/config'
import accountingConfig from '@/frontend/features/accounting/config'
import inventoryConfig from '@/frontend/features/inventory/config'
import crmConfig from '@/frontend/features/crm/config'
import platformAdminConfig from '@/frontend/features/platform-admin/config'

const featureConfigs: FeatureConfig[] = [
  overviewConfig,
  communicationsConfig,
  statusConfig,
  aiConfig,
  workspaceStoreConfig,
  knowledgeConfig,
  contactConfig,
  databaseConfig,
  documentsConfig,
  menuStoreConfig,
  calendarConfig,
  userManagementConfig,
  reportsConfig,
  tasksConfig,
  formsConfig,
  approvalsConfig,
  supportConfig,
  projectsConfig,
  auditLogConfig,
  importExportConfig,
  integrationsConfig,
  posConfig,
  builderConfig,
  marketingConfig,
  analyticsConfig,
  biConfig,
  automationConfig,
  salesConfig,
  hrConfig,
  contentConfig,
  cmsLiteConfig,
  accountingConfig,
  inventoryConfig,
  crmConfig,
  platformAdminConfig,
]
/**
 * Extract and validate all discovered features
 */
export const DISCOVERED_FEATURES: FeatureConfig[] = [...featureConfigs].sort(
  (a, b) => a.ui.order - b.ui.order
)

/**
 * Get all registered features
 */
export function getAllFeatures(): FeatureConfig[] {
  return DISCOVERED_FEATURES
}

/**
 * Get feature by ID
 */
export function getFeatureById(id: string): FeatureConfig | undefined {
  const findFeature = (features: FeatureConfig[]): FeatureConfig | undefined => {
    for (const feature of features) {
      if (feature.id === id) return feature
      if (feature.children) {
        const found = findFeature(feature.children)
        if (found) return found
      }
    }
    return undefined
  }
  return findFeature(DISCOVERED_FEATURES)
}

/**
 * Get features by category
 */
export function getFeaturesByCategory(category: string): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.ui.category === category)
}

/**
 * Get features by type (default, optional, etc.)
 */
export function getFeaturesByType(
  type: 'default' | 'system' | 'optional' | 'experimental'
): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.technical.featureType === type)
}

/**
 * Get features by status
 */
export function getFeaturesByStatus(
  status: 'stable' | 'beta' | 'development' | 'experimental' | 'deprecated'
): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.status.state === status)
}

/**
 * Get all ready features (isReady = true)
 */
export function getReadyFeatures(): FeatureConfig[] {
  return DISCOVERED_FEATURES.filter(f => f.status.isReady)
}

/**
 * Get all feature IDs (flat list)
 */
export function getAllFeatureIds(): string[] {
  const collectIds = (features: FeatureConfig[]): string[] => {
    return features.flatMap(f => [f.id, ...(f.children ? collectIds(f.children) : [])])
  }
  return collectIds(DISCOVERED_FEATURES)
}

/**
 * Get features by bundle ID and role
 * @param bundleId - The bundle ID to filter by
 * @param role - Optional: 'core' | 'recommended' | 'optional'
 */
export function getFeaturesByBundle(
  bundleId: string,
  role?: 'core' | 'recommended' | 'optional'
): FeatureConfig[] {
  const flattenFeatures = (features: FeatureConfig[]): FeatureConfig[] => {
    return features.flatMap(f => [f, ...(f.children ? flattenFeatures(f.children) : [])])
  }
  
  return flattenFeatures(DISCOVERED_FEATURES).filter(feature => {
    if (!feature.bundles) return false
    
    if (role) {
      return feature.bundles[role]?.includes(bundleId as any) ?? false
    }
    
    return (
      feature.bundles.core?.includes(bundleId as any) ||
      feature.bundles.recommended?.includes(bundleId as any) ||
      feature.bundles.optional?.includes(bundleId as any)
    )
  })
}

/**
 * Get core features for a bundle (cannot be disabled)
 */
export function getBundleCoreFeatures(bundleId: string): FeatureConfig[] {
  return getFeaturesByBundle(bundleId, 'core')
}

/**
 * Get recommended features for a bundle (enabled by default)
 */
export function getBundleRecommendedFeatures(bundleId: string): FeatureConfig[] {
  return getFeaturesByBundle(bundleId, 'recommended')
}

/**
 * Get optional features for a bundle (disabled by default)
 */
export function getBundleOptionalFeatures(bundleId: string): FeatureConfig[] {
  return getFeaturesByBundle(bundleId, 'optional')
}

/**
 * Validate registry for duplicates and issues
 */
export function validateRegistry(): { valid: boolean; errors: string[] } {
  const errors: string[] = []
  const ids = getAllFeatureIds()
  const duplicates = ids.filter((id, index) => ids.indexOf(id) !== index)

  if (duplicates.length > 0) {
    errors.push(`Duplicate feature IDs found: ${duplicates.join(', ')}`)
  }

  const paths = DISCOVERED_FEATURES.map(f => f.ui.path)
  const duplicatePaths = paths.filter((path, index) => paths.indexOf(path) !== index)
  if (duplicatePaths.length > 0) {
    errors.push(`Duplicate paths found: ${duplicatePaths.join(', ')}`)
  }

  return {
    valid: errors.length === 0,
    errors,
  }
}

/**
 * Backward compatibility exports
 * @deprecated Use DISCOVERED_FEATURES instead
 */
export const FEATURES_REGISTRY = DISCOVERED_FEATURES

/**
 * Convert to legacy features.config.ts format
 * @deprecated Will be removed when legacy manifest is retired
 */
export function toLegacyFormat() {
  return DISCOVERED_FEATURES.map(f => ({
    slug: f.id,
    name: f.name,
    description: f.description,
    featureType: f.technical.featureType,
    category: f.ui.category,
    icon: f.ui.icon,
    path: f.ui.path,
    component: f.ui.component,
    order: f.ui.order,
    type: 'route' as const,
    version: f.technical.version,
    hasUI: f.technical.hasUI,
    hasConvex: f.technical.hasConvex,
    hasTests: f.technical.hasTests,
    tags: f.tags,
    status: f.status.state,
    isReady: f.status.isReady,
    children: f.children?.map(c => ({
      slug: c.id,
      name: c.name,
      description: c.description,
      featureType: c.technical.featureType,
      category: c.ui.category,
      icon: c.ui.icon,
      path: c.ui.path,
      component: c.ui.component,
      order: c.ui.order,
      type: 'route' as const,
      version: c.technical.version,
      hasUI: c.technical.hasUI,
      hasConvex: c.technical.hasConvex,
      hasTests: c.technical.hasTests,
    })),
  }))
}

if (process.env.NODE_ENV !== 'production') {
  const validation = validateRegistry()
  if (!validation.valid) {
    console.error('Feature Registry Validation Failed:')
    validation.errors.forEach(err => console.error(`  - ${err}`))
  } else {
    console.log(`Feature Registry: ${DISCOVERED_FEATURES.length} features discovered`)
  }
}

